### ISSUE TITLE
Add support for python-dotenv at the config level

### ISSUE THREAD

**Issue by PatrickAlphaC** [eth-brownie/brownie#1000]
### Overview
I'd love to see brownie support a `.env` file for environment variables. For new engineers, or a project that doesn't want to keep a ton of environment variables running, a `.env` file is a warm welcome. Truffle and Hardhat (the javascript smart contract frameworks) have really nice config files that allow them to work with .env files. A bit of a quality of life improvement.

Otherwise, we have to call in the `.env` file in all our script manually, seems pretty redundant to do so. 

### Specification
Not sure how this is normal done in yaml, but would like to see something like:
`dotenv: true`

And then they can load via a `.env` file. We could just use https://pypi.org/project/python-dotenv/ to load at the start of all the scripts.

### Dependencies
https://pypi.org/project/python-dotenv/

What do we think?

**Comment by iamdefinitelyahuman** [comment]
I see no harm in checking for the existence of this file when loading a project, and processing it if it's found.

**Comment by omarish** [comment]
Would it make sense if the value of the `dotenv` key in the YAML config is a path instead of a boolean? That way you can specify if you're using a different dotenv.

**Comment by PatrickAlphaC** [comment]
Ooooo. That's much better

**Comment by omarish** [comment]
Cool. And @iamdefinitelyahuman, do you think the dotenv file should be a) auto-loaded, or b) loaded only if `dotenv:` is specified in the YAML config?

**Comment by PatrickAlphaC** [comment]
I vote for loading only if it's specified.

**Comment by skellet0r** [comment]
Loading only if explicitly opted in via the YAML config sounds better to me. Sort of how docker-compose allows one to load an env-file or multiple. Plus, security wise might be better to opt-in 🤔 

https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option

**Comment by omarish** [comment]
I agree. I'd just like to get buy-in from @iamdefinitelyahuman before building something out. 

When it comes to crypto projects, I'm an advocate for configuration over convention. Writing an extra line in a config file is a great price to pay, especially if it means avoiding unexpected configuration behavior.

**Comment by iamdefinitelyahuman** [comment]
Sounds good to me! I agree that the explicitness of adding a line to the config is better than potential accidentally... some config settings.

**Comment by omarish** [comment]
Excellent. Another realization is that this should probably support interpolating envvars in the config, like this:

## `.env file`:

```
DEFAULT_NETWORK=development
```

## `brownie-config.yaml`:

```yaml
networks:
  default: ${DEFAULT_NETWORK}
```

**Comment by omarish** [comment]
@iamdefinitelyahuman I have something basic up, but 1) it's not quite working yet, and 2) I'm still thinking about what should be in charge of loading the env file. It seems like a responsibility of `main.py`. An earlier implementation I had done was loading it in the config container, but I don't think the config container should be in charge of something stateful like loading an env file.

That said, if we do want to support POSIX-style variable interpolation, we'd probably want access in the ConfigContainer level so that we only have to parse once.

Thoughts?

**Comment by PatrickAlphaC** [comment]
> Excellent. Another realization is that this should probably support interpolating envvars in the config, like this:
> 
> ### `.env`:
> ```
> DEFAULT_NETWORK=development
> ```
> 
> ## `brownie-config.yaml`:
> ```yaml
> dotenv: ./.env
> networks:
>   default: ${DEFAULT_NETWORK}
> ```
> 
> Double-checking that this makes sense to you, @iamdefinitelyahuman and @PatrickAlphaC?

Yes. 100%. This was something that I was surprised didn't work by default. This will be a massive improvement adding that to the yaml.

**Comment by gnattishness** [comment]
As I didn't see this mentioned previously, [direnv](https://direnv.net/) is an alternative to having brownie process `.env` files on its own.

Its a tradeoff between suggesting users install a separate tool and increasing the amount of things brownie needs to do.
(Though I don't have a particular opinion either way)

**Comment by omarish** [comment]
Makes sense. I can add this in; should be pretty straightforward. Sorry for the delay, recently made the `2to3` family migration and just getting back into my routine now.

**Comment by PatrickAlphaC** [comment]
Congratulations!!
