### ISSUE TITLE
Cant't deploy contract properly on BSC

### ISSUE THREAD

**Issue by forestswap** [eth-brownie/brownie#1008]
### Environment information

* `brownie` Version: 14.2
* Python Version: 3.8.5
* OS: MacOS Big Sur (Tried on a Debian VPS too)

### What was wrong?

After thorough testing on BSC-main-fork and testnet, where everything works seamlessly, I deployed my contracts on Bsc-Mainnet. I have two contracts : token and master (of the token).

Compiling is OK, Token deployment works, but not Master where I'm stuck on a perpetual "Waiting for confirmation..." :

```python
master = Master.deploy(token.address, {"from":acct}, publish_source=True)
```

```
Transaction sent: 0x4f29f5b3a26a0eab08ae90756e24942154c0219076623afc7d9ecc0905e3f73c
  Gas price: 10.0 gwei   Gas limit: 2384969   Nonce: 6
Waiting for confirmation... 
````
Here's the log : https://bscscan.com/tx/0x4f29f5b3a26a0eab08ae90756e24942154c0219076623afc7d9ecc0905e3f73c

I've tried to start another session console and recover the deployed contract using the abi with Master.at([address]), but then Brownie just freezes.

Do you have any idea what is happening ? Could it be a RPC problem ?

[edit] : I deployed it through Truffle and verified it. Interestingly enough, running this freezes Brownie too :
```python
master = Contract.from_explorer("0x6E8d868F4a973F198162d638b6970f657B51f0c4")
````

**Comment by iamdefinitelyahuman** [comment]
Looked at this - seems the public BSC node that Brownie uses doesn't support filtering, so the caching functionality added in `1.14.0` bricks everything :(

I think a fix will be quite simple so I should be able to have a new version out shortly.  In the short term though, you can get around it by adding `web3._remove_middlewares()` as the first line in your script.  Or just downgrade to `1.13.4` until a new version releases.

**Comment by iamdefinitelyahuman** [comment]
Update: installing from `master` should now fix this.  I'll try to get a new version on pypi soon.
