### ISSUE TITLE
Dependencies for hypothesis, pytest and web3 are outdated

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#1010]
### Overview
The latest versions of `hypothesis`, `pytest` and `web3` all break functionality somewhere in Brownie.

### Specification
Someone needs to bump each dependency to the latest version, fix the failing tests, and play around in the console / run some large test suites to make sure there is no further weirdness.  This could be a big-ish job, given the level of hackiness and touching-private-APIs that brownie does with `pytest` and `hypothesis` :grimacing:

**Comment by Maxence-L** [comment]
Does that mean testing doesn't work with v1.14.5 ?
