### ISSUE TITLE
Add support for EIP-155 (ChainID)

### ISSUE THREAD

**Issue by coinyon** [eth-brownie/brownie#1021]
### Overview

I'm trying to use Brownie with vanilla Geth v1.10 and transactions abort with:

> only replay-protected (EIP-155) transactions allowed over RPC

### Specification

It looks like EIP-155 demands to have the chainId included into the tx/signature. Brownie should probably do that.

### Dependencies

* See section "ChainID enforcement" in https://blog.ethereum.org/2021/03/03/geth-v1-10-0/

### Workaround

* Use geth with `--rpc.allow-unprotected-txs`

**Comment by iamdefinitelyahuman** [comment]
This seems like a problem better solved in `web3.py` - and i wonder, maybe they already have solved and it just means we need to bump the version on this end?

**Comment by iamdefinitelyahuman** [comment]
Sorry, i didn't correctly understand how/where this was happening.  Moved to Geth 1.10 and witnessed first hand and then finally got it :)  Fixed in #1056.

**Comment by coinyon** [comment]
Awesome, thx
