### ISSUE TITLE
[hardhat] brownie reverts context manager does not catch reverts

### ISSUE THREAD

**Issue by WyseNynja** [eth-brownie/brownie#1027]
### Environment information

* `brownie` Version: 48d3f182747dc7807c4d6149024b519dd7215061
* `hardhat` Version: 2.1.3-dtt.0 sha512-QWI3LbImf5vyshQzC2nGxzkgtMHsK5BovcWUMgNl3f/0QGCtVRLhTvkA6/FK0f8XhDkFCOHLsJmyRrt4Ao9grg==
* `solc` Version: 0.8.3
* Python Version: 3.9.2
* OS: osx and linux

### What was wrong?

I'm testing out swapping ganache-cli for hardhat@dtt on the [argobytes](https://github.com/SatoshiAndKin/argobytes-contracts) repo.

One of my tests expects a revert, but it is not being caught.

```
        with brownie.reverts(""):
>           argobytes_proxy_clone.execute(action, {"from": accounts[1]})
E           ValueError: Transaction reverted without a reason

tests/test_argobytes_clone.py:26: ValueError
```

### How can it be fixed?

My guess is that ganache errors were not ValueErrors like hardhat's are. Either change hardhat errors to match ganache, or update the context manager to catch ValueErrors.

**Comment by iamdefinitelyahuman** [comment]
A quick solution (on the hardhat side) is to add this to the project config:

```javascript
module.exports = {
   networks: {
      hardhat: {
         throwOnTransactionFailures: false,
         throwOnCallFailures: false
      }
   }
}
```

But surely we can find a solution in Brownie without requiring this.
