### ISSUE TITLE
brownie run ./scripts/token.py results in FileNotFoundError

### ISSUE THREAD

**Issue by stnbu** [eth-brownie/brownie#1073]
### Environment information

* `brownie` Version: 1.14.6
* `ganache-cli` Version: 6.12.2
* `solc` Version: 0.8.3+commit.8d00100c.Emscripten.clang
* Python Version: 3.7.3
* OS: debian linux 10.9 (buster)

### What was wrong?

Following the the documentation, I cannot get the token.py deploy script to run (cannot locate it). The file is there, but `FileNotFoundError` is raised.

```
(venv3.7) mburr@presence:~/brown$ mkdir /tmp/brownie
(venv3.7) mburr@presence:~/brown$ cd /tmp/brownie
(venv3.7) mburr@presence:/tmp/brownie$ brownie init
Brownie v1.14.6 - Python development framework for Ethereum

SUCCESS: A new Brownie project has been initialized at /tmp/brownie
(venv3.7) mburr@presence:/tmp/brownie$ brownie bake token
Brownie v1.14.6 - Python development framework for Ethereum

Downloading from https://github.com/brownie-mix/token-mix/archive/master.zip...
9.13kiB [00:00, 6.65MiB/s]
SUCCESS: Brownie mix 'token' has been initiated at /tmp/brownie/token
(venv3.7) mburr@presence:/tmp/brownie$ brownie compile
Brownie v1.14.6 - Python development framework for Ethereum

Project has been compiled. Build artifacts saved at /tmp/brownie/build/contracts
(venv3.7) mburr@presence:/tmp/brownie$ brownie run ./token/scripts/token.py
Brownie v1.14.6 - Python development framework for Ethereum

BrownieProject is the active project.
Attached to local RPC client listening at '127.0.0.1:8545'...
  File "/home/mburr/git/brownie/brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "/home/mburr/git/brownie/brownie/_cli/run.py", line 45, in main
    path, _ = _get_path(args["<filename>"])
  File "/home/mburr/git/brownie/brownie/project/scripts.py", line 130, in _get_path
    raise FileNotFoundError(f"Cannot find {path_str}")
FileNotFoundError: Cannot find ./token/scripts/token.py
```

Thinks of note:

* Using a python virtualenv bootstrapped from the system python3.7 binary
* Have my own repo of brownie and used `pip3 install -e .` so that it is editable
* Tried again after blowing away `~/.brownie`. Same results.
* My investigation got as far as `brownie/utils/docopt.py`. docopt does not appear to be finding argv[2] (the path).

### How can it be fixed?

It looks like `docopt()` is returning `None` here: https://github.com/eth-brownie/brownie/blob/aaffc21c4445566f66d71deed95b0e8f47391771/brownie/_cli/run.py#L34 that needs to be diagnosed.

**Comment by stnbu** [comment]
I might just be _assuming_ the above is supported. Things seem to behave when I `cd ./token`. Feel free to close this issue if this is not supported.

**Comment by iamdefinitelyahuman** [comment]
I believe the issue is that you're trying to run the script when your current working directory is outside the project's root directory.

**Comment by stnbu** [comment]
Yeah, you're right. I thought there might be additional magic to accommodate what I'm doing. But I'm assuming a lot and we probably don't need more magical python surprising people.

**Comment by DanielHarbours** [comment]
> I believe the issue is that you're trying to run the script when your current working directory is outside the project's root directory.

Hey im having the same issue. Can you tell me how to get my working directory into my projects root directory?
