### ISSUE TITLE
If ganache-cli cannot be used, don't auto-select another network. Tell the user what is happening.

### ISSUE THREAD

**Issue by stnbu** [eth-brownie/brownie#1075]
### Overview

If an RPC client is already running and attached to `127.0.0.1:8545`, brownie will by default use that instead of starting `ganache-cli`. This caused some confusion for me. The first time I experimented with brownie, it would launch `ganache-cli` for me (as described in the docs). At a later point in time, with geth running and attached to port 8545, brownie tells me it is using it:

```
$ brownie console
Brownie v1.14.6 - Python development framework for Ethereum

BrowniePlayProject is the active project.
/mypath/main.py:46: BrownieEnvironmentWarning: Development network has a block height of 4716187
  BrownieEnvironmentWarning,
Attached to local RPC client listening at '127.0.0.1:8545'...
Brownie environment is ready.
>>>
```

Since the default behavior changes depending on whether that address is already in use, it think it would be better for brownie to tell you so and refuse to start. If I start `ganache-cli` it says:

```
$ ganache-cli
Ganache CLI v6.12.2 (ganache-core: 2.13.2)
Error: listen EADDRINUSE: address already in use 127.0.0.1:8545
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at doListen (net.js:1461:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

If brownie refused to start and said something like `cannot launch ganache-cli ... address already in use 127.0.0.1:8545` (or something), it would have been more apparent what's happening and I wouldn't be surprised by what's in `accounts` for example.

For a new, inexperienced user, it would be _less_ confusing to stop and tell you `ganache-cli` cannot be started than to just use whatever is listening to the address that was requested by `ganache-cli`.

### Specification

Something like this would be nice:

```
$ brownie console
Brownie v1.14.6 - Python development framework for Ethereum

BrowniePlayProject is the active project.
FATAL: cannot launch ganache-cli, address already in use 127.0.0.1:8545
```

**Comment by iamdefinitelyahuman** [comment]
This behavior exists because users coming from truffle are trained that `ganache-cli` must first be launched as a separate process.  Brownie has no easy way to check _what_ it's connecting to, it simply checks if a connection is possible at the given address and port.  The warning `Development network has a block height of 4716187` is provided for users in your situation.

**Comment by stnbu** [comment]
> provided for users in your situation.

Good enough. Thanks for the response.
