### ISSUE TITLE
[hardhat] Reverted transaction require debug_traceTransaction to be able to debug

### ISSUE THREAD

**Issue by dimitar-petrov** [eth-brownie/brownie#1083]
### Overview
I am getting this error on hardhat branch when a transaction is reverted:
`ipdb> history[-1].events
*** brownie.exceptions.RPCRequestError: Accessing `TransactionReceipt.events` on a reverted transaction requires the `debug_traceTransaction` RPC endpoint, but the node client does not support it or has not made it available.
`
What is the current way to debug transactions on hardhat-fork network. I am not very familiar with hardhad.
It would be great of someone can point me to best practices for debugging solidity.

My goal is to have a fast feedback loop during contract development when it needs to interact with forked network.
Thanks.

**Comment by iamdefinitelyahuman** [comment]
The hardhat branch is still a work in progress.  It hasn't been merged yet because some aspects are not ready.
