### ISSUE TITLE
Downloaded solc binary cannot be compiled in OSX

### ISSUE THREAD

**Issue by nkitlabs** [eth-brownie/brownie#1086]
### Environment information

* `brownie` Version: 1.14.6
* `ganache-cli` Version: 6.12.2
* `solc` Version: 0.6.12
* Python Version: 3.9.5
* OS: osx (chip Apple M1)

### What was wrong?

I try to run _`$brownie test`_ or _`$brownie console`_ but got the error below. It seems that the downloaded solc binary file cannot be compiled. This also happened when I try to run in the project with the solidity version 0.8.4. However, when I run _`$brownie console`_ outside the solidity project, there is no issue and can use it normally.

```bash
brownie test
Brownie v1.14.6 - Python development framework for Ethereum

Downloading from https://solc-bin.ethereum.org/macosx-amd64/solc-macosx-amd64-v0.6.12+commit.27d51765
100%|██████████████████████████████████████| 33.8M/33.8M [00:35<00:00, 944kiB/s]
  File "brownie/test/plugin.py", line 87, in pytest_load_initial_conftests
    active_project = project.load(project_path)
  File "brownie/project/main.py", line 745, in load
    return Project(name, project_path)
  File "brownie/project/main.py", line 180, in __init__
    self.load()
  File "brownie/project/main.py", line 235, in load
    self._compile(changed, self._compiler_config, False)
  File "brownie/project/main.py", line 92, in _compile
    build_json = compiler.compile_and_format(
  File "brownie/project/compiler/__init__.py", line 105, in compile_and_format
    find_solc_versions(solc_sources, install_needed=True, silent=silent)
  File "brownie/project/compiler/solidity.py", line 173, in find_solc_versions
    install_solc(*to_install)
  File "brownie/project/compiler/solidity.py", line 105, in install_solc
    solcx.install_solc(version, show_progress=True)
  File "solcx/install.py", line 466, in install_solc
    raise exc
  File "solcx/install.py", line 459, in install_solc
    _validate_installation(version, solcx_binary_path)
  File "solcx/install.py", line 636, in _validate_installation
    raise SolcInstallationError(
SolcInstallationError: Downloaded binary would not execute, or returned unexpected output. If this issue persists, you can try to compile from source code using `solcx.compile_solc('0.6.12')`.
```

I looked into [this issue](https://github.com/eth-brownie/brownie/issues/904) but upgrading macos version doesn't help for this case.

Any suggestion,

Thanks.

**Comment by nkitlabs** [comment]
Update: Solved. To address this, link(alias) the python command to brew's python3.

**Comment by PatrickAlphaC** [comment]
@nkitlabs what was the command you ran to get this per chance?

**Comment by parth7326** [comment]
> Update: Solved. To address this, link(alias) the python command to brew's python3 and reinstall brownie with brew's pipx.

how to use brew's pipx to install brownie?

**Comment by heydamali** [comment]
If you ever run into this issue consider downloading python3 version 3.8.10 (specifically). My Mac book (apple M1 chip) came with python3 version 3.8.9 and for some reason, it never worked until I followed [this](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/issues/985#issuecomment-1034441763) issue and upgraded to 3.8.10 and everything worked.


For how to download python3 version 3.8.10, visit the official python download site https://www.python.org/downloads/
