### ISSUE TITLE
ModuleNotFoundError: No module named 'brownie._cli'

### ISSUE THREAD

**Issue by chiku524** [eth-brownie/brownie#1095]
I have installed all of the dependencies for eth-brownie, installed the actual package but when I try to run _brownie_ in the terminal, I receive the ModuleNotFoundError. I have tried reinstalling brownie and upgrading it via pipx, but I still get the same error. Am I doing something wrong? 

Here is a screenshot of the errors I am receiving.

![image](https://user-images.githubusercontent.com/61144399/120225990-4a807880-c214-11eb-9b89-46ecfbdfd042.png)

**Comment by chiku524** [comment]
Turns out I had it installed both using pipx and pip, so I'm sure they were creating complications with each other. 

Will be closing this issue out.

**Comment by jmarty-cyber** [comment]
Currently facing the same issue.
Did it work after you uninstalled one?
And Which one did you uninstall?

**Comment by chiku524** [comment]
Hey @jmarty-cyber! Sorry for the late response

It did end up working, and if I remember correctly I uninstalled both versions of pip and reinstalled pipx.

I only chose to reinstall pipx over pip because pipx is the newer version of pip, but I think it will work with any of the two.

Hope this helps and feel free to ask any other questions you may have

**Comment by jmarty-cyber** [comment]
I didn’t realize you responded.
I will give it a try and let you know.

Thank you!
