### ISSUE TITLE
Fetch from explorer error on Matic

### ISSUE THREAD

**Issue by vfurci200** [eth-brownie/brownie#1103]
### Environment information

* `brownie` Version: 1.14.6
* `ganache-cli` Version: 6.12.2
* `solc` Version: 0.6.6
* Python Version: 3.8.3
* OS: osx/linux

### Network information
live:
- name: Polygon
  networks:
    - name: Mainnet
      chainid: 137
      id: polygon-main
      host: https://rpc-mainnet.maticvigil.com/
      explorer: https://explorer.matic.network

### What was wrong?

Contract.from_explorer function does not work on matic. 
e.g.
`wMATIC= Contract.from_explorer('0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270');`
which also causes any deployment to give out the error. 

Fetching source of 0xb7a4F3E9097C08dA09517b5aB877F7a917224ede from explorer.matic.network...
  File "<console>", line 1, in <module>
  File "brownie/project/scripts.py", line 69, in run
    return func(*args, **kwargs)
  File "./scripts/deploy_contracts.py", line 51, in main
    usdc = Contract.from_explorer("0xb7a4F3E9097C08dA09517b5aB877F7a917224ede")
  File "brownie/network/contract.py", line 1090, in from_explorer
    data = _fetch_from_explorer(address, "getsourcecode", silent)
  File "brownie/network/contract.py", line 1890, in _fetch_from_explorer
    raise ConnectionError(f"Status {response.status_code} when querying {url}: {response.text}")
ConnectionError: Status 503 when querying https://explorer.matic.network/: <!DOCTYPE HTML>

...
  <title>Just a moment...</title>
 

</head>
<body>
    
    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> maticvigil.com.</h1>
    
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>
   
  ...
     
  

  
  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=6593e1776ea70f56')"> </div>
</div>

          
          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>6593e1776ea70f56</code></span>
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>

### How can it be fixed?

Requests seem to be blocked by Cloudflare...
How do you fetch contracts from explorer for Curve?

**Comment by iamdefinitelyahuman** [comment]
Matic's block explorer doesn't offer an API for querying contracts in the same way that etherscan does.  I believe they're working to get etherscan support, but for now this functionality simply isn't possible.  This is why polygon isn't an officially supported sidechain.

I would suggest asking the matic team about etherscan support.

**Comment by vfurci200** [comment]
thank you @iamdefinitelyahuman, that makes sense I will ask them
