### ISSUE TITLE
Handle new error types for solidity 0.8.4

### ISSUE THREAD

**Issue by BlinkyStitt** [eth-brownie/brownie#1108]
https://blog.soliditylang.org/2021/04/21/custom-errors/

This post has some example ethers js code that should be a decent guide.

**Comment by iamdefinitelyahuman** [comment]
Was this fixed in #1110 ?

**Comment by cameel** [comment]
I think that #1110 made Brownie not crash on them but did not add any way to parse the info out of them and display it to the user.

**Comment by julianmrodri** [comment]
HI, im having trouble parsing custom errors in my tests. Im using solc `0.8.4` and I get the following error when trying to parse the revert reason. Is there a plan to support this in the short term? Should I be using the `brownie.reverts` in a different way? Thanks!

```
  with brownie.reverts("CustomErrorMessage()"):
        token.issue(mintAmount, {'from': owner})
```       
I get this error:
```
 - AssertionError: Unexpected revert string 'typed error: 0xd9a6bff9'
```

**Comment by EdNoepel** [comment]
In case it is useful, I created some sample contracts and tests surrounding this:
https://github.com/EdNoepel/brownie-test-issues/blob/master/tests/test_errors.py

Note that when a custom error is raised by an imported/library contract, the exception and callstack does not reveal details about the error.

**Comment by damn1** [comment]
Hey guys @julianmrodri workaround works perfect but does anybody knows how to do something like that when errors have parameters? If I have an error for example like this `error AddressNotAdmin(address addr);`, the revert message is like `typed error: 0x0888870300000000000000000000000033a4622b82d4c04a53e170c638b944ce27cffce3`. Do you how that hash is built? Thanks

**Comment by cameel** [comment]
The selector is built the same way as for functions, i.e. includes parameter types. I.e. for your `AddressNotAdmin` error the selector is created by hashing `AddressNotAdmin(address)`.

**Comment by michprev** [comment]
This is not exactly a solution for this issue but you should give a try to the new Python-based testing framework that was inspired by Brownie - [Woke testing framework](https://ackeeblockchain.com/woke/docs/latest/testing-framework/overview/) (spoiler alert - I am the lead developer). It handles user-defined errors in a form of dataclass exceptions. To do this, pytypes , Python equivalents of Solidity types with type hints, are generated which also provide autocompletions while writing tests in Python.

**Comment by JoaoMorais96** [comment]
> 'typed error: ' +

did the keccak function change? this does not seem to work anymore

**Comment by JoaoMorais96** [comment]
To anybody still struggling with this, I submitted a pull request.
In the meanwhile (or if it is not approved) you can use this function in your testing:
```
from eth_utils.abi import function_abi_to_4byte_selector, collapse_if_tuple
def encode_custom_error(contract_, err_name, params):

    contract_abi = contract_.abi

    for error in [abi for abi in contract_abi if abi["type"] == "error"]:
        # Get error signature components
        name = error["name"]
        data_types = [collapse_if_tuple(abi_input) for abi_input in error.get("inputs", [])]
        error_signature_hex = function_abi_to_4byte_selector(error).hex()
 
        if err_name == name:
            encoded_params = ''
            for param in params:
                if(type(param)==str):
                    return('typed error: 0x'+error_signature_hex+param.zfill(66)[2:])
                elif(type(param)==int):
                    val = "{0:#0{1}x}".format(param,66)
                    val = val[2:]
                else:
                    return 'Unsupported type'
                encoded_params = encoded_params + val
            return('typed error: 0x'+error_signature_hex+encoded_params)
```

For example if you want to test if a function checkIfPar(uint256 num) in your contract NumberGetter throws the error numberNotPa(num), for num = 10, you would do:
```
with brownie.reverts(encode_custom_error('NumberGetter', 'numberNotPar ', [10])):
        NumberGetterdeploy.checkIfPar(10
                                        {"from":accounts[0]})
```
