### ISSUE TITLE
remapping sub directory path

### ISSUE THREAD

**Issue by israel-perez** [eth-brownie/brownie#1116]
### Environment information

* `brownie` Version: v1.14.2

I have problem to remapping sub directory path:

remappings: 
  - '@uniswap/v2-core=Uniswap/uniswap-v2-core@1.0.1'

**Comment by srulikpy** [comment]
i have tried also a direct import:
import '@Uniswap/uniswap-lib@1.1.4/contracts/libraries/FixedPoint.sol'

but still:
ParserError: Source "@Uniswap/uniswap-lib@1.1.4/contracts/libraries/FullMath.sol" not found: File outside

**Comment by maxsiz** [comment]
try this:  `import 'Uniswap/uniswap-lib@1.1.4/contracts/libraries/FixedPoint.sol'`

**Comment by srulikpy** [comment]
It works. Thanks. So only direct import works? I will not be able to use remapping?

**Comment by maxsiz** [comment]
You can do that  but you need  add some in config. Please read details in the doc https://eth-brownie.readthedocs.io/en/stable/compile.html?highlight=remapping#remapping-installed-packages
