### ISSUE TITLE
brownie console loading failed 

### ISSUE THREAD

**Issue by yujianFresh** [eth-brownie/brownie#1124]
### Environment information

* `brownie` Version: 1.14.6
* `ganache-cli` Version: 6.12.2
* `solc` Version: x.x.x
* Python Version: 3.8.10
* OS: osx

### What was wrong?
when i  run `brownie console` 
it shows 
```
Brownie v1.14.6 - Python development framework for Ethereum

BrownieTokenTemplateProject is the active project.

Launching 'ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...
```
this take long time , nothing to happen .

anyone can help me ?

Please include information like:

* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* full output of the error you received

### How can it be fixed?

Fill this in if you know how the bug could be fixed.

**Comment by yujianFresh** [comment]
<img width="963" alt="screenshot" src="https://user-images.githubusercontent.com/24457810/123388940-f2972080-d5cb-11eb-836e-fd1825114e91.png">

it show like this, nothing else to happen

**Comment by PatrickAlphaC** [comment]
How many contracts are in your contracts folder?

**Comment by yujianFresh** [comment]
> How many contracts are in your contracts folder?

it only two files, and this repo was cloned by cli `brownie bake`

**Comment by PatrickAlphaC** [comment]
What was the mix that you baked? Maybe there is an issue there.

Could you delete the folder, rebake, and see if you get the same issue? ie, just run:

```
brownie bake xxxxx
cd xxxxx
brownie console
```

**Comment by yujianFresh** [comment]
it's because of my network failed, now it's work well.
