### ISSUE TITLE
brownie project import error in visual studio code

### ISSUE THREAD

**Issue by yujianFresh** [eth-brownie/brownie#1128]
<img width="825" alt="screenshot" src="https://user-images.githubusercontent.com/24457810/123610066-d2b56600-d832-11eb-96b1-d4bd9d45f7e8.png">

it shows like this . how can i fix it ? i already run `brownie pm install OpenZeppelin/openzeppelin-contracts@3.4.0`

**Comment by yujianFresh** [comment]
it's only shows error in vscode, `brownie compile` run well in cmd.

**Comment by iamdefinitelyahuman** [comment]
Same response as https://github.com/yearn/yearn-vaults/issues/424#issuecomment-869666361 - closing this
