### ISSUE TITLE
OVM Support

### ISSUE THREAD

**Issue by fubuloubu** [eth-brownie/brownie#1151]
### Overview
Optimism has soft launched their mainnet and will begin allowing anyone to deploy to it soon. It would be excellent if Brownie could support it. 

Related:
https://github.com/eth-brownie/brownie/issues/934

**Comment by karask** [comment]
+1

Optimism Kovan is already available to all. Adding the network is trivial but optimism requires a different solc compiler...

**Comment by smartcontracts** [comment]
Custom compiler no longer required! Created #1362 to get OE added to `network-config.yaml`. Would love if someone could try deploying/verifying an OE project with Brownie once merged :-)

**Comment by poolpitako** [comment]
@fubuloubu I think this can be closed. Optimism works fine in brownie.
