### ISSUE TITLE
Add .env to .gitignore after `brownie init`

### ISSUE THREAD

**Issue by PatrickAlphaC** [eth-brownie/brownie#1168]
### Overview

Add `.env` to .gitignore after `brownie init`

So that people who use environment variables can have a little more protection.

**Comment by iamdefinitelyahuman** [comment]
Sounds good!

**Comment by ptisserand** [comment]
Hi @iamdefinitelyahuman, could I work on this issue ?

**Comment by iamdefinitelyahuman** [comment]
gladly :)

**Comment by ptisserand** [comment]
Hi @iamdefinitelyahuman do you think it's necessary to add .gitignore content checking in tests/project/main/test_main_project.py ?
