### ISSUE TITLE
Namespace collision

### ISSUE THREAD

**Issue by RusAlex** [eth-brownie/brownie#1171]
### Environment information

* `brownie` Version: 1.15.2
* `ganache-cli` Version: 6.12.2
* `solc` Version: 0.8.4+commit.c7e474f2.Linux.g++
* Python Version: 3.8.7
* OS: linux

### What was wrong?

Please include information like:

```
Foo.sol
pragma solidity ^0.8.4;
contract Foo {
    address public _owner;

    constructor (address tokenOwner)  payable {
        _owner = tokenOwner;
    }
}
```

```
script/first.py
import brownie;
account = brownie.accounts.load('testnet')

def main():
  account.deploy(brownie.Foo, account.address)
```

then I type *brownie run scripts/first.py* and see this error:
```
pipx/venvs/eth-brownie/lib64/python3.8/site-packages/brownie/network/contract.py:793: BrownieEnvironmentWarning: Namespace collision between contract function and brownie `Contract` class member: 'Foo._owner'
The _owner function will not be available when interacting with Foo
  warnings.warn(
Terminating local RPC client...
```

### How can it be fixed?

Fill this in if you know how the bug could be fixed.

**Comment by iamdefinitelyahuman** [comment]
This is unfortunately not fixable without a major refactor of Brownie.
