### ISSUE TITLE
Built-In Alchemy support

### ISSUE THREAD

**Issue by PatrickAlphaC** [eth-brownie/brownie#1177]
Right now, Infura is the default for environment variables and connecting to accounts.

Forking from infura right now is _really_ slow, but I've found forking from Alchemy to be *much* quicker. 

Perhaps having a built-in `ALCHEMY_MAINNET_URL`  environment variable would be nice too. Or `ALCHEMY_PROJECT_ID`.

Might be a little tricky to support both though... This is definitely just a "nice to have"

**Comment by iamdefinitelyahuman** [comment]
Yes this seems really useful, especially for upcoming hardhat support - i know they recommend alchemy.

**Comment by willianpaixao** [comment]
@iamdefinitelyahuman @PatrickAlphaC I believe this issue can be closed.
