### ISSUE TITLE
forkedmain for other chains?

### ISSUE THREAD

**Issue by 1blockologist** [eth-brownie/brownie#1213]
I would like there to be options or flags for forkedmain of other networks besides Ethereum mainnet. Is this currently possible?

**Comment by skellet0r** [comment]
Check the docs:
https://eth-brownie.readthedocs.io/en/stable/network-management.html

As well as the default network config:
https://github.com/eth-brownie/brownie/blob/master/brownie/data/network-config.yaml#L128-L139
