### ISSUE TITLE
Skipping tests with `@pytest.mark.skip()` fails with `-s` option

### ISSUE THREAD

**Issue by shuklaayush** [eth-brownie/brownie#1215]
### Environment information

* `brownie` Version: 1.16.1
* Python Version: 3.9.6
* OS: linux

### What was wrong?

Skipping tests with `@pytest.mark.skip()` and `-s` option results in pytest crashing and a long `INTERNALERROR` trace. I've added a minimal reproducible example here: https://github.com/shuklaayush/brownie-skip-test

```python
# tests/test_skip.py

@pytest.mark.skip()
def test_skip():
    assert True

def test_noskip():
    assert True
```

### Steps to reproduce
```bash
# Clone repo
git clone git@github.com:shuklaayush/brownie-skip-test.git
cd brownie-skip-test
# First test is skipped and second passes as expected
brownie test
# Second test doesn't run and pytest crashes
brownie test -s
```
I think it has something to do with pytest running teardown even for skipped tests, but not sure

**Comment by iamdefinitelyahuman** [comment]
Might be something to do with the custom printing logic applied from `-s`.
