### ISSUE TITLE
Add arbitrum/arbitrum-fork support

### ISSUE THREAD

**Issue by shuklaayush** [eth-brownie/brownie#1230]
### Overview
Looks like Arbitrum forking doesn't work out of the box (either with ganache-cli or hardhat). Running a simple tx on a local fork sometimes reverts, or gives an RPC error (`invalid argument 1: json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes`)

I've created an example repo here to demonstrate: https://github.com/shuklaayush/brownie-arbitrum-error

### Specification
Similar to how Polygon/xDai was added

### Dependencies
Probably ganache and/or hardhat

**Comment by dalton-cole** [comment]
This issue was closed but arbitrum fork support is not native.
