### ISSUE TITLE
Import "brownie" could not be resolved

### ISSUE THREAD

**Issue by Bug-terminator** [eth-brownie/brownie#1340]
### Environment information
Win10 WSL2 VSCode

* `brownie` Version: 1.17.1
* `ganache-cli` Version: None
* `solc` Version:  0.8.9
* Python Version: 3.8.5
* OS: win10

### What was wrong?
The Pylance can't find where the brownie is, so the Python code can't auto-complete(In fact ,there is a wave line under brownie and said "Import 'brownie' could not be resolved"). However, everything works fine when I run `brownie run scripts/my_script.py`, so what's the problem, and how to fix it?
PS: The Python interpreter is exactly which I use to install pipx, and I use pipx to install brownie.

**Comment by timfam** [comment]
How did you resolve this issue?
