### ISSUE TITLE
Support Ganache v7

### ISSUE THREAD

**Issue by banteg** [eth-brownie/brownie#1351]
ganache v7.0.0-beta.0 just dropped with multiple breaking changes which need to be addressed for it to work with brownie

https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-beta.0

**Comment by sambacha** [comment]
Dockerfile support running confirmed

**Comment by sambacha** [comment]
Also see https://github.com/eth-brownie/brownie/issues/1334

**Comment by iamdefinitelyahuman** [comment]
Support for ganache v7 is added in the `v1.18.0` release

**Comment by sambacha** [comment]
Woot
