### ISSUE TITLE
ValueError: Gas estimation failed: 'execution reverted: VM Exception while processing transaction' 

### ISSUE THREAD

**Issue by AnneCh** [eth-brownie/brownie#1358]
## Environment information

* `brownie` Version: v1.17.1
* `ganache-cli` Version: v6.12.2 
* `solc` Version: @0.6.0
* Python Version: 3.9.9
* OS: windows

I've been following and writing along Patrick Collin's incredibly packed lesson on Youtube on Blockchain and Solidity. 
I'm at the stage where I want to run a script called fund_and_withdraw on my local Ganache account through creating mocks.

I have correctly added the ganache-local network to the networks list of Brownie, as when I run my deploy.py script, it works perfectly.

Yet, when I try to run the fund_and_withdraw.py script, the fund function seemed to be running, but not the withdraw part. As I have found someone who had the same issue, my problem evolved since I followed the advice from this [post 422](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/422) from @GratefulDave. 

Like him, the error message was  `ValueError: Execution reverted during call: 'execution reverted: VM Exception while processing transaction: invalid opcode'. This transaction will likely revert. If you wish to broadcast, include 'allow_revert:True' as a transaction parameter.`

### Attempt to fix it through changing the network ID on Ganache

I followed one of the advice, which was to change my network ID on my local Ganache server, after deleting ganache-local from the list of Brownie's networks. I did so, and re-added ganache-local networks with updated host and chainid.

Then the error was different, as this time, the entry fee couldn't even be taken, and this error message came:
#### Current error message
```S C:\Users\chret\Documents\demo\brownie_fund_me> brownie run scripts/fund_and_withdraw.py --network ganache-local
INFO: Could not find files for the given pattern(s).
Brownie v1.17.1 - Python development framework for Ethereum

BrownieFundMeProject is the active project.

Running 'scripts\fund_and_withdraw.py::main'...
0
The current entry fee is 0
Funding
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\_cli\run.py", line 50, in main
    return_value, frame = run(
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\project\scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File ".\scripts\fund_and_withdraw.py", line 22, in main
    fund()
  File ".\scripts\fund_and_withdraw.py", line 12, in fund
    fund_me.fund({"from": account, "value": entrance_fee})
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\contract.py", line 1625, in __call__
    return self.transact(*args)
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\contract.py", line 1498, in transact
    return tx["from"].transfer(
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\account.py", line 652, in transfer
    receipt, exc = self._make_transaction(
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\account.py", line 735, in _make_transaction
    raise VirtualMachineError(e) from None
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\exceptions.py", line 125, in __init__
    raise ValueError(str(exc)) from None
ValueError: Gas estimation failed: 'execution reverted: VM Exception while processing transaction: revert You need to spend more ETH!'. This transaction will likely
revert. If you wish to broadcast, you must set the gas limit manually.
```

 I do have enough ETH to process those transactions, so the error message is very confusing to me.

### What else I've tried

Since this message appeared, I've tried removing my entire code, from all documents (deploy.py, helpful_scripts.py, fund_and_withdraw.py, FundMe.sol, brownie-config.yaml) and pasted Patrick's codes. 

The same error message came through.

Here is a link to my[ repo](https://github.com/AnneCh/Solidity-16h-FCC) with the relevant documents.

Any help is appreciated! 

Have a good day ahead 
(excuses in advance in the formatting of this post isn't great, I'm still new around here but I'll learn fast!)

Anne

**Comment by GratefulDave** [comment]
I am also experiencing the same issue:

Environment:
Brownie v.1.17.1
Ganache CLI v6.12.2 (ganache-core: 2.13.2)
Node v16.8.0
Npm v7.21.0
Truffle v5.0.22
Python 3.98
OS: macOS Monterey 12.1 Beta. 

I've provided a trace & a call trace from the brownie console [here](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/422).

**Comment by AnneCh** [comment]
Update, I've run the following commands:
```
$ npm uninstall ganache-cli --global
$ npm install ganache@alpha --global
```

and now the entry fee is grabbing the correct number, the contract is called and shows on my Ganache transaction page, but the withdraw function still doesn't work. So, I fixed the problem I had created when changing the chainID on Ganache, back to the original problem where brownie tells me 
```
 File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\_cli\run.py", line 50, in main
    return_value, frame = run(
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\project\scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File ".\scripts\fund_and_withdraw.py", line 23, in main
    withdraw()
  File ".\scripts\fund_and_withdraw.py", line 18, in withdraw
    fund_me.withdraw({"from": account})
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\contract.py", line 1625, in __call__
    return self.transact(*args)
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\contract.py", line 1498, in transact
    return tx["from"].transfer(
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\account.py", line 652, in transfer
    receipt, exc = self._make_transaction(
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\account.py", line 735, in _make_transaction
    raise VirtualMachineError(e) from None
  File "C:\Users\chret\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\exceptions.py", line 125, in __init__
    raise ValueError(str(exc)) from None
ValueError: Gas estimation failed: 'execution reverted: VM Exception while processing transaction: invalid opcode'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.
```

Any idea what is causing this?

**Comment by sagara11** [comment]
same problem i just get 
![image](https://user-images.githubusercontent.com/50282671/144470355-5d2b128a-232e-4597-a795-44de536633cd.png)
can some one resolve it pls :(

**Comment by sagara11** [comment]
![image](https://user-images.githubusercontent.com/50282671/144470497-93d161b9-a9a6-4df9-b86f-3e0c2710915e.png)

**Comment by AnneCh** [comment]
@sagara11 did you try what I did on my last comment? That solved the issue of "spending more Eth", the entry fee got to 25000000, but it withdraw function still does not run though..

**Comment by sagara11** [comment]
@AnneCh i did the same your comment but i still got entranceFee = 0 :(

**Comment by sagara11** [comment]
![image](https://user-images.githubusercontent.com/50282671/144574199-8d09035a-75c7-40aa-b21d-05a022e29254.png)
here is my snippet of code can u check it for me ?

**Comment by AnneCh** [comment]
@sagara11 yup, looks fine to me, I cannot see the parenthesis closed on the last line of your fund() function, but I assume that's just the screenshot doing that.
 I have the exact same code, which is the exact same code as @PatrickAlphaC. I have literally replaced all my code with his to check it out, and the same error (gas estimation failed) came back.

At this point, it seems more like a problem of compatibility between versions of some of the programs we have, either Ganache, solidity compiler or God knows what. I'm totally new to coding so I won't be able to help you more than that I'm afraid :/

**Comment by sagara11** [comment]
@AnneCh okay thanks for your help so i guess i would move to lesson 7, totally regret to not continue following lesson 6 :(

**Comment by AnneCh** [comment]
WAIT! I think I got it!!

**Comment by sagara11** [comment]
@AnneCh tell me buddy =))))

**Comment by AnneCh** [comment]
@sagara11 @GratefulDave have you tried setting up a new workspace on Ganache?
I just did it, set up 8000000 as a gas limit, and it worked.

Process:

-delete ganache-local from your brownie networks list
- delete the corresponding folders on build/deployments/1337(or whatever your chainID was) as well as the corresponding chainid lines of the map.json file

- on your Ganache instance, instead of clicking on the quicklaunch, click on create workspace
- Set up the gas limit to a higher number than it is currently at (I chose 8000000), the rest can stay as it is

- on your VSC terminal, or whatever program you use to type your code, re-introduce the network ganache-local (`brownie networks add Ethereum ganache-local host=http://YOURHOSTNUMBER chainid=YOURCHAINID`

- I gave it a test with my deploy.py contract, it worked
- Now run your fund_and_withdraw

Let me know if that works for you !

@GratefulDave it does seem like the gas limit was the problem after all, but not to change on the script itself, rather, on the Ganache interface

**Comment by sagara11** [comment]
@AnneCh still doesn't work, it drive me crazy ...

**Comment by sagara11** [comment]
![image](https://user-images.githubusercontent.com/50282671/144579678-2e464acf-16fe-4265-96e4-35a82aa4d7bd.png)
although i set up gas limit to a number that bigger than the number you suggest but still got nothing...

**Comment by AnneCh** [comment]
damn... yeah I get the frustration, I lost 5 days of learning time because of that.
I hope someone will suggest something that works.

Good luck, and don't get discouraged, that is part of the process, as (future) developers, our roles include a LOT of troubleshooting. Don't give up!

**Comment by sagara11** [comment]
@AnneCh thanks buddy, it's so meaningful to me, i will go for it. Good luck to u too pal !

**Comment by sagara11** [comment]
@AnneCh 
![image](https://user-images.githubusercontent.com/50282671/144583974-ce16c03b-3371-47e3-a952-0228f833ef82.png)
just realize that if i push directly number 2500000 it works perfectly fine so the problem is fund_me.getEntranceFee() return nothing, so i supposed that fund_me is not yet being called ???

**Comment by sagara11** [comment]
fund_me variable is an address of FundMe contract but in the context i think it need contract object in order to implement getEntranceFee() method

**Comment by AnneCh** [comment]
mmmh interesting. I gotta admit I don't know enough to tell you why it's working when you enter the number directly, but yeah it does look like it's a problem between your fund_and_withdraw function and your FundMe contract. 

that's way beyond my scope of very limited knowledge at this point, but I'm curious to understand the mechanism behind it, if someone comes around here and would be kind enough to explain :) 

that being said, kudos for finding a workaround!! Now you can get to the testing part!! 💯

**Comment by GratefulDave** [comment]
I am not an expert, but a there should be some way to calculate maximum gas fee a contract should use. In addition to that, I would venture to guess that these contracts being relatively simple should not use that much gas.

**Comment by GratefulDave** [comment]
I've even set gas price to 1 and max gas 999999999999999.

**Comment by GratefulDave** [comment]
@AnneCh Nope. I've tried changing the gas fee. It continues to fail.

**Comment by AnneCh** [comment]
@GratefulDave Damn.... I hope @PatrickAlphaC or someone of his caliber can help you out soon. I assume you also posted on other platforms, like StackExchange or StackOverflow ?

**Comment by GratefulDave** [comment]
Yes, I posted to:

https://ethereum.stackexchange.com/questions/114889/deploying-ganache-local-w-brownie-vm-exception-while-processing-transaction-in

And

https://github.com/trufflesuite/ganache-ui/issues/3524

**Comment by AnneCh** [comment]
Keep me posted

**Comment by PatrickAlphaC** [comment]
I thumbed up your error on the truffle site, hopefully that will fix this.

**Comment by WeTheArtist** [comment]
Hi All, the same issue here, but I noticed that my entrance fee shows as 2500000, while in the video it shows as 25000000000000000, so maybe there is an issue with the getEntraceFee function
![Capture](https://user-images.githubusercontent.com/79281462/146072369-6ee5e622-cf2f-4e6b-8f4c-f885ffb1b721.PNG)
?

**Comment by ghostofcoolidge** [comment]
> Hi All, the same issue here, but I noticed that my entrance fee shows as 2500000, while in the video it shows as 25000000000000000, so maybe there is an issue with the getEntraceFee function ![Capture](https://user-images.githubusercontent.com/79281462/146072369-6ee5e622-cf2f-4e6b-8f4c-f885ffb1b721.PNG) ?

So this is actually the issue.  When I manually changed it to 25*10**18, it started working.  This function is what is causing the issue.  Somewhere, the trailing zeros in the solidity contract and/or Fund_and_withdrawy.py script are not matching.
![image](https://user-images.githubusercontent.com/74361147/151588395-1ca3ee83-25cc-4449-9400-7ed2c60a9858.png)

**Comment by lfsr** [comment]
> @AnneCh i did the same your comment but i still got entranceFee = 0 :(

Maybe you don't have a return statement in the getEntranceFee() function in your contract? Had the same issue
