### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 559: character maps to <undefined>

### ISSUE THREAD

**Issue by SpiritBob** [eth-brownie/brownie#1426]
### Environment information

* `brownie` Version: x.x.x
* `ganache-cli` Version: Ganache CLI v6.12.2 (ganache-core: 2.13.2)
* `solc` Version: x.x.x
* Python Version:  3.10.2
* OS: Windows 10

### What was wrong?
When I run `pipx install eth-brownie` I get the follwoing error:
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\appdata\roaming\python\python310\scripts\pipx.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pipx\main.py", line 779, in cli
    return run_pipx_command(parsed_pipx_args)
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pipx\main.py", line 202, in run_pipx_command
    return commands.install(
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pipx\commands\install.py", line 60, in install
    venv.install_package(
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pipx\venv.py", line 238, in install_package
    subprocess_post_check_handle_pip_error(pip_process)
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pipx\util.py", line 349, in subprocess_post_check_handle_pip_error
    print(completed_process.stderr, file=pip_error_fh, end="")
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 559: character maps to <undefined>
```

**Comment by Ashu2k** [comment]
I had the same issue. It looks like `eth-brownie` has some issue with python version `3.10`
Try running it with `python 3.9.10`. It worked for me.

And make sure that your `pyvenv.cfg` file is pointing to the right version & directory of python i.e. `3.9.10` in this case
This file can be found in `C:\Users\<username>\.local\pipx\shared` for windows

**Comment by capit0** [comment]
Ok so I follow Ashu2ks advice. But now I get this error:

```
PS C:\Users\User\Documents\Blockchain\web3_py_simple_storage> pipx install eth-brownie
No Python at 'C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe'
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\User\.local\pipx\logs\cmd_2022-02-08_17.15.03_pip_errors.log

Error installing eth-brownie.
```

**Comment by Ashu2k** [comment]
@capit0  your `pipx` is still pointing to `Python.3.10`. You need to make sure that it points to version 3.9

Find the file named `pyvenv.cfg` and change the `home `and `version `variables in it.

It should look something like this

`home = C:\Users\<Your UserName>\AppData\Local\Programs\Python\Python39
include-system-site-packages = false
version = 3.9.10`

**Comment by capit0** [comment]
@Ashu2k The weird thing is, it is already looking like that:

```
home = C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0
include-system-site-packages = false
version = 3.9.10
```

But it keeps saying:

```
No Python at 'C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe'
```

I even tried reinstalling all libraries + deinstalling all python versions and reinstalling them. Are there any other things I can try?

**Comment by Ashu2k** [comment]
@capit0 I am sorry I don't know the exact reason why you are facing this problem. But it's clear from the error message that somewhere your env variable is pointing to a different version of python. I am not an expert on this matter. But here is something that I found on google.

[https://www.freecodecamp.org/news/manage-multiple-python-versions-and-virtual-environments-venv-pyenv-pyvenv-a29fb00c296f/](url)

Try changing the environment variable or creating a virtual environment.

**Comment by SpiritBob** [comment]
@capit0 I had the same issue. Just delete your pipx folder and try again. Should work.

**Comment by RomanRemez** [comment]
python 3.9.10 worked for me too
had to remove 3.10 
also removed C:\Users\username\.local\pipx\shared\Scripts\pip310
