### ISSUE TITLE
Contract.transfer method is raising unexpected AttributeError 

### ISSUE THREAD

**Issue by DJercic** [eth-brownie/brownie#1434]
### Environment information

* `brownie` Version:  v1.17.2
* `ganache-cli` Version: 7.0.2
* `solc` Version: 0.8.0
* Python Version: 3.9.10
* OS: linux (wsl2)

### What was wrong?

I've used a brownie Token mix template and generated a basic RFC20 token. When I run the tests (without any prior modification of the code) I get the a couple of failed tests with the following exception:

```python
 AttributeError: 'NoneType' object has no attribute '_with_attr'
```
I've tracked down the root of the issue and it lies in `brownie.network.account._PrivateKeyAccount.transfer`.
Problem starts on line 644 when the function calls `self._make_transaction` and expects back a  `Tuple[TransactionReceipt, Optional[Exception]]` which is fine and in this case the exception that is returned is `None` a few lines later that exception is passed in the next method `receipt._raise_if_reverted(exc)` and the typings for that method suggest that None is not expected (although debatable because None can be considered Any?)

file: `brownie.network.transaction.TransactionReceipt`
```python
 def _raise_if_reverted(self, exc: Any) -> None:
    # and later on line 446 exc is accessed like it's always defined. 
```
 
Example of the test file (this is taken directly from the generated token template) 

```python
from typing import List
import brownie

from brownie.network.contract import Contract
from brownie.network.account import Account

def test_insufficient_balance(accounts: List[Account], token: Contract):
    balance = token.balanceOf(accounts[0])
    with brownie.reverts() as error:
        token.transfer(accounts[1], balance + 1, {'from': accounts[0]})
```

### How can it be fixed?

It seems that the expected state of the TransactionReceipt is that it is revered when it hits the `_raise_if_reverted` method (nice naming btw) but inside the exception is None. The obvious fix would be either to pass the exception from TransactionReceipt , or based on the design to initiate a default exception when situation like this occurs? Also, I would add more strict typings to the `_raise_if_reverted` method:
```python
 def _raise_if_reverted(self, exc: Exception) -> None:
    # ....
```
or 

```python
 def _raise_if_reverted(self, exc: Optional[Exception]) -> None:
    # ....
```
(depends on the solution that is chosen)

If you spare the time it would be nice to fix this so the test case does not have to catch AttributeError instead of actual brownie exceptions 😄 

Anyway, hope I helped at least in some way!

**Comment by theref** [comment]
I have also run into this issue, but only when running brownie within Docker

**Comment by ahbanavi** [comment]
I have the same problem while running tests:

```python
def test_set_price_reverts(contract):
    with brownie.reverts():
        contract.setPrice(0)
```

errors:
```
FAILED tests/deploy_test.py::test_set_price_reverts - AttributeError: 'NoneType' object has no attribute '_with_attr'
```
![image](https://user-images.githubusercontent.com/39927312/153755706-9bd60a68-bade-4095-b831-215e3a442d60.png)

Python 3.9.10
Brownie v1.17.2
