### ISSUE TITLE
Brownie does not function after upgrade from a version 1.17.2 to 1.18.1

### ISSUE THREAD

**Issue by haraslub** [eth-brownie/brownie#1457]
### Environment information

* `brownie` Version: 1.18.1
* `ganache-cli` Version: 6.12.2 (ganache-core: 2.13.2)
* `solc` Version: py-solc-x-1.1.1
* Python Version: 3.9.7
* OS: win11

### What was wrong?

After upgrading Brownie from version 1.17.2 to 1.18.1, Brownie has stoped functioning properly.  Once I run commands like `brownie compile`, `brownie console`, `brownie run scripts/deploy.py`, `brownie test` it does nothing. See the following lines extracted from bash. Interestingly, old projects already built works perfectly + commands like `brownie networks` list or `brownie accounts` works as well. 

What am I missing, please?

```
my_computeri@LAPTOP-VVKHNKSN MINGW64 ~/demos/aave_uni_sushi
$ brownie compile
Brownie v1.18.1 - Python development framework for Ethereum

my_computer@LAPTOP-VVKHNKSN MINGW64 ~/demos/aave_uni_sushi
$
```

```
my_computer@LAPTOP-VVKHNKSN MINGW64 ~/demos/aave_uni_sushi
$ brownie console
Brownie v1.18.1 - Python development framework for Ethereum

my_computer@LAPTOP-VVKHNKSN MINGW64 ~/demos/aave_uni_sushi
$
```

```
my_computer@LAPTOP-VVKHNKSN MINGW64 ~/demos/aave_uni_sushi
$ brownie run scripts/sushiswap_deploy.py
Brownie v1.18.1 - Python development framework for Ethereum

my_computer@LAPTOP-VVKHNKSN MINGW64 ~/demos/aave_uni_sushi
$
```

**Comment by haraslub** [comment]
Hm, it will not be probably caused by the upgrade itself. Brownie does not function anymore even though I downgraded (reinstalled/uninstalled+reinstalled) to the 17.2.1 version. But I do not have idea how to find out the cause.

**Comment by jasonklein** [comment]
@haraslub: I think I'm dealing with the same issue. Have you managed to resolve it?

I found that with a basically initialized repo (e.g., has an empty `contracts/` directory), commands like `brownie compile` and `brownie console` appear to succeed. But if I add a simple file like `contracts/Test.sol` containing, "contract Test {}", then those commands hang. For me, this is true across versions 1.18.1, 1.18.0, 1.17.2, and 1.16.4.

**Comment by haraslub** [comment]
@jasonklein Unfortunately, I have not managed to resolve it. Do you also have WIN 11? I guess that the update from WIN 10 to WIN 11 might be the cause.

**Comment by jasonklein** [comment]
@haraslub: no, I'm on macOS Monterey.

I am new-ish to python, and so I thought maybe the issue might be in my setup. However, I saw that others reported a similar issue on Gitter [here](https://gitter.im/eth-brownie/community?at=621fcc2bf43b6d783fe19cb5) and Discord [here](https://discord.com/channels/809793915578089484/809794189193773057/953090343799250945).

**Comment by jasonklein** [comment]
@haraslub: I found a solution, though I can't pretend I understand it. The issue was due to the `request` python package stalling with the request to get the list of Solidity compiler versions for my OS. Based on [this](https://stackoverflow.com/a/70315217/3770675) SO answer, I turned my router and WiFi off and on and that seems to have resolved the issue.

**Comment by haraslub** [comment]
@jasonklein unfortunately, it has not worked, but reinstallation of brownie has.
