### ISSUE TITLE
Downgrade `typing-extensions` to match with latest `py-evm` requirements

### ISSUE THREAD

**Issue by PARABRAHMAN0** [eth-brownie/brownie#1527]
### Overview

It becomes impossible to you use the latest brownie versions with other packages such as gnosis-py for the reason that brownie dependencies are not in line with the requirements of the latest version of py-evm.

The version in question seems to have been bumped here -> https://github.com/eth-brownie/brownie/commit/5661274f4dd26df5e9444fa63f97c164c6d1986b

Pkg managers such as poetry will throw the following:

```bash
  Because no versions of eth-brownie match >1.18.1,<2.0.0
   and eth-brownie (1.18.1) depends on typing-extensions (4.0.1), eth-brownie (>=1.18.1,<2.0.0) requires typing-extensions (4.0.1).
  And because trie (2.0.0a5) depends on typing-extensions (>=3.7.4,<4), eth-brownie (>=1.18.1,<2.0.0) is incompatible with trie (2.0.0a5).
  And because py-evm (0.5.0a3) depends on trie (2.0.0-alpha.5)
   and no versions of py-evm match >0.5.0a3, eth-brownie (>=1.18.1,<2.0.0) is incompatible with py-evm (>=0.5.0a3).
  And because gnosis-py (3.9.3) depends on py-evm (>=0.5.0a3)
   and no versions of gnosis-py match >3.9.3,<4.0.0, eth-brownie (>=1.18.1,<2.0.0) is incompatible with gnosis-py (>=3.9.3,<4.0.0).
  So, because olymsig depends on both gnosis-py (^3.9.3) and eth-brownie (^1.18.1), version solving failed.
```

So yes I believe typing-extensions could be downgraded to <4 since it seems to have been bumped regularly and new functionality isn't explicitly necessary unless it interferes with other dependencies?

### Specification
N/A

### Dependencies
Is above.

**Comment by iamdefinitelyahuman** [comment]
Dependencies were updated in #1530, removing the requirement for `typing-extensions`.
