### ISSUE TITLE
[Bug] Can't use brownie console with anvil to deploy contracts 

### ISSUE THREAD

**Issue by 0xfarhaan** [eth-brownie/brownie#1549]
### Environment information

* `brownie` Version: 1.19.0
* `solc` Version: 0.8.10
* Python Version: 3.9.7
* OS: osx

### What was wrong?

Please include information like:
Can't deploy contracts using the accounts object with anvil as I get a "to" key error 

* what command you ran
The command I ran was 
```
brownie console --network anvil
```
The error in the console and the code that lead to it. 

```python
>>> from brownie import *
>>> accounts[0].deploy(MockCurveOracle)
Transaction sent: 0xedbbeef98ae3fcad52be3bd2244d62c6cfba48ada5c39b18b365453bdf1d6a09
  File "<console>", line 1, in <module>
  File "brownie/network/account.py", line 510, in deploy
    receipt, exc = self._make_transaction(
  File "brownie/network/account.py", line 759, in _make_transaction
    receipt = TransactionReceipt(
  File "brownie/network/transaction.py", line 199, in __init__
    self._set_from_tx(tx)
  File "brownie/network/transaction.py", line 549, in _set_from_tx
    self.receiver = EthAddress(tx["to"]) if tx["to"] else None
  File "web3/datastructures.py", line 51, in __getitem__
    return self.__dict__[key]  # type: ignore
KeyError: 'to'
```

**Comment by farhaan-ali** [comment]
@WyseNynja tagging you as I saw you did the PR to add anvil to brownie (thank you btw!) maybe you know what's the issue.

**Comment by fala13** [comment]
When trying to launch anvil separately and have brownie attach to it, I get this:
```
method = 'evm_increaseTime', args = [0]

    def _request(method: str, args: List) -> int:
        try:
            response = web3.provider.make_request(method, args)  # type: ignore
            if "result" in response:
                return response["result"]
        except (AttributeError, RequestsConnectionError):
            raise RPCRequestError("Web3 is not connected.")
>       raise RPCRequestError(response["error"]["message"])
E       brownie.exceptions.RPCRequestError: invalid type: integer `0`, expected a (both 0x-prefixed or not) hex string with length between (0; 64]

env/lib/python3.10/site-packages/brownie/network/rpc/ganache.py:130: RPCRequestError
```

**Comment by WyseNynja** [comment]
For the first one, I'm guessing anvil doesn't return anything for "to" when it's ZERO_ADDRESS. That should be easy to handle in brownie, but at first glance it seems like an anvil bug. 

For your second error, anvil is strict about wanting hex encoded integers for seemingly everything. For the "chain.sleep" and similar chain commands I do this encoding for the user. Maybe we need a middleware to make it automatic for more commands. Or maybe anvil could be less strict in its parsing.

**Comment by fala13** [comment]
For the second error to me the crucial part is brownie detecting the already running RPC as ganache, while in this rpc dir is also anvil.py:
`env/lib/python3.10/site-packages/brownie/network/rpc/ganache.py:130: RPCRequestError`
and the --network flag doesn't seem to matter when there is already RPC running on same machine.

**Comment by WyseNynja** [comment]
I'm pretty sure there's no "detection" of the underlying rpc. It just assumes it's ganache if it's connecting to an already running rpc because that's all that used to exist. Adding something to check the client would be a good idea.

**Comment by fala13** [comment]
Foundry guys checked that when invoked with curl "to" in in the returned json as null, so this needs to be fixed on brownie side after all.

PS. with my hack above I'm often getting anvil errors "intristic gas price too high", so not a smooth ride after this.

**Comment by WyseNynja** [comment]
Ah. So they return null when everyone else is returning zero address. Brownie can handle this, but it's a change compared to the other rpcs.

**Comment by charles-cooper** [comment]
@0xfarhaan should be fixed, please reopen if not
