### ISSUE TITLE
test fails on "incorrect number of arguments" passed when correct number was passed.

### ISSUE THREAD

**Issue by 0xFlexure** [eth-brownie/brownie#1557]
### Environment information

* `brownie` Version: 1.18.1
* `ganache-cli` Version: 7.0.4
* `solc` Version: 0.8.10
* Python Version: 3.9.10
* OS: osx

### What was wrong?

I have a test where this is happening. The function takes one address, and here I pass it one address. But I get a type error that it was given two and only takes one.

If I pass it zero arguments, then it works, returning a value of 0. 

```
>     bank_token_x_bal_t0 = bank.balance(token_x)
E     TypeError: balance() takes 1 positional argument but 2 were given
```

The method is derived from a public mapping
`  mapping (address => uint) public balances;`

The contract instance is from deploying the contract, not wrapping an already deployed address with the contract or an interface or anything else. 

This is in a standard `brownie test`.

**Comment by 0xFlexure** [comment]
I deleted the build folder, built again, and still same behavior.

**Comment by abdullathedruid** [comment]
Not sure if this is a typo, but your mapping is `balances` and the function you are calling is `balance`.

**Comment by 0xFlexure** [comment]
That's right - I was thinking it was just `balance`. And `balance` is a thing in brownie for getting the ETH balance off an address, hence why this didn't fail completely. Would there have been a problem if it was just named `balance`, too? Don't know but at least now I do know `balance` in brownie is a built-in thing to any address.

**Comment by abdullathedruid** [comment]
> That's right - I was thinking it was just `balance`. And `balance` is a thing in brownie for getting the ETH balance off an address, hence why this didn't fail completely. Would there have been a problem if it was just named `balance`, too? Don't know but at least now I do know `balance` in brownie is a built-in thing to any address.

I don't know this for certain, but I think if you create a function called `balance` in a smart contract, brownie recognises this and renames the balance built-in to `wei_balance`
