### ISSUE TITLE
web3 v6 support

### ISSUE THREAD

**Issue by dspicher** [eth-brownie/brownie#1669]
### Overview
I would like to use brownie with the beta release of `web3 6.0.0`, which [has been released in March of this year](https://pypi.org/project/web3/#history). Is anybody already working on this? If not, would you welcome a PR?

**Comment by fellu** [comment]
Looks like PR might be welcomed? :3

**Comment by iamdefinitelyahuman** [comment]
Support for web3 v6 added in `v1.20.0`.
