### ISSUE TITLE
Vyper 0.3.8 support

### ISSUE THREAD

**Issue by vykintasmak** [eth-brownie/brownie#1693]
Hey, currently requirements.txt has vyper version set to 0.3.7. Theres already 0.3.8 as well as this contradicts the statement in the readme that brownie supports vyper >=0.1.0-beta.16

Can this requirement be updated or are there any issues why its set specifically to 0.3.7?

**Comment by iamdefinitelyahuman** [comment]
Bumped in `v1.20.0`
