### ISSUE TITLE
scripts won't run on 1.20.0

### ISSUE THREAD

**Issue by bayou020** [eth-brownie/brownie#1739]
### Environment information

* `brownie` Version: 1.20.0
* `ganache-cli` Version: 7.8.0
* `solc` Version: 0.8.19
* Python Version: 3.12.1
* OS: osx

### What was wrong?

Please include information like:
while trying to run scripts on brownie i got this error
`
  File "brownie/_cli/__main__.py", line 62, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/run.py", line 36, in main
    args = docopt(__doc__, more_magic=True)
  File "brownie/utils/docopt.py", line 809, in docopt
    assert instr.opname.startswith("CALL_")
AssertionError: `
while it was running correctly on 1.19.5

**Comment by iamdefinitelyahuman** [comment]
Fixed in #1738, i'll push out a patch release with the fix soon
