### ISSUE TITLE
Improve documentation for Brownie Mixes

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#323]
### Overview
The only mention of Brownie mixes in the docs is a single line within the installation section.  This could be improved.

### Specification
1. Add a section (or at least a subsection) specific to Brownie mixes.  It should include:
    1. What they are and why they're useful
    2. Where to find them
    3. How to install them
    4. How to create your own mix
2. Create an issue template for proposing new mixes, and come up with a standard process for new contributors who wish to create and maintain one.

### Dependencies
None.

**Comment by carlfarterson** [comment]
I can definitely help with this :smile:
