### ISSUE TITLE
Install packages with non-standard folder structures

### ISSUE THREAD

**Issue by WyseNynja** [eth-brownie/brownie#497]
### Overview

I am wanting to install [kollateral](https://github.com/kollateral/kollateral) as a dependency, but it has a different project structure than brownie expects.

The repo also does not have any git tags.

### Specification

`.../main.py` has `if not install_path.joinpath("contracts").exists():`. For now I've just commented this out, since contracts is just deeper in the project, but I think having this be a configurable value would work well.

For the lack of tags, it would be nice if we could just specify a full git hash.

**Comment by iamdefinitelyahuman** [comment]
1. Truffle has a `contracts_directory` setting in the [config file](https://www.trufflesuite.com/docs/truffle/reference/configuration#contracts_directory). Adding something like this to Brownie, and then globbing to determine the contracts folder, would probably work.
2. :+1: to the idea of using a git hash when a tag isn't available.

**Comment by iamdefinitelyahuman** [comment]
Split this issue into two tasks - #578 focuses on the required change for the folder structure.  This issue is specific to globbing, and installation via hash.

Both of these are targetted for the next minor release.
