### ISSUE TITLE
Failing codecov status checks in CI

### ISSUE THREAD

**Issue by thomasrockhu** [eth-brownie/brownie#559]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by iamdefinitelyahuman** [comment]
Hi @thomasrockhu, thanks for the headsup!  I enabled the app, but now codecov has added itself to the CI and keeps failing builds from a lack of coverage.  I don't recall enabling this feature, and I don't see an obvious way to disable it.  Could you point me in the right direction?  :pray:

**Comment by thomasrockhu** [comment]
Hi @iamdefinitelyahuman taking a look now!

**Comment by thomasrockhu** [comment]
Hi @iamdefinitelyahuman just to get some clarity here. Are your CI builds failing or are you seeing failed status checks on your PRs? If it's failed CI builds, could you link me to one?

**Comment by iamdefinitelyahuman** [comment]
It's a failed status check. Here's an example: https://github.com/iamdefinitelyahuman/brownie/pull/564

There are 2 new CI jobs, `codecov/patch` and `codecov/project` that are both failing because the coverage diff is too low.  While I appreciate having this information, I'd rather not have a drop in coverage cause that a PR or commit to be labelled as failing.

**Comment by thomasrockhu** [comment]
Got it, the product team took a quick look and the most likely reason is that the original setup was not correct, and by switching to the app, it self-corrected.

If you would prefer to not have this happen, I can open a PR to add a `codecov.yml` file in your repo. It would contain

```
coverage:
  status:
    project:
      informational: true
    patch:
      informational: true
```

Let me know if you prefer to do this

**Comment by iamdefinitelyahuman** [comment]
that would be perfect :+1:

**Comment by thomasrockhu** [comment]
Here you go @iamdefinitelyahuman https://github.com/iamdefinitelyahuman/brownie/pull/565

**Comment by iamdefinitelyahuman** [comment]
Still getting failed status checks...  reopening this issue for now as a reminder to deal with it.  @thomasrockhu if you have any insight it's much appreciated! But you've already gone above and beyond here so no worries if not, I'm sure the documentation will reveal a solution :)

**Comment by thomasrockhu** [comment]
Hi @iamdefinitelyahuman, just wanted to check in here and see what I could do to help! Did switching to `target: 0` work for you?

**Comment by iamdefinitelyahuman** [comment]
Yep, solved it :)  Thanks for checking!
