### ISSUE TITLE
Errors from no archival state can be confusing

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#573]
### What was wrong?
When using `--fork` with a non-archival node there is a ~30 minute window until errors begin to occur from not having access to archival state:

```
ValueError: {'message': 'Returned error: project ID does not have access to archive state', 'code': -32000, 'data': {'stack': 'Error: Returned error: project ID does not have access to archive state\n    at Object.ErrorResponse (/home/computer/.npm-packages/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1421880)\n    at /home/computer/.npm-packages/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1420752\n    at t.n.onreadystatechange (/home/computer/.npm-packages/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:89:10247)\n    at t.e.dispatchEvent (/home/computer/.npm-packages/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:17:47987)\n    at t._setReadyState (/home/computer/.npm-packages/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:89:15283)\n    at t._onHttpResponseEnd (/home/computer/.npm-packages/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:89:18380)\n    at IncomingMessage.<anonymous> (/home/computer/.npm-packages/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:89:17635)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)', 'name': 'Error'}}
```

Once aware of this issue the cause is fairly obvious, but this could be surprising and confusing for a new user.

### How can it be fixed?
Add a layer to the `web3` middleware that catches this specific error, checks if the active network is using `--fork`, and if yes delivers an easier to understand error.

**Comment by WyseNynja** [comment]
So Infura is doing something special to make this error. If you are forking from your own node that doesn't have archive data, the error is instead something about `missing trie node`

Thankfully [running your own fast synced geth node with archive state](https://gist.github.com/WyseNynja/89179917d209d10e6ea27c5f2f8f88f1) is pretty easy. No need for all the archive state.

**Comment by iamdefinitelyahuman** [comment]
If you end up on one of your non-archive nodes and hit the `missing trie` error, please dump it here for reference :pray:

**Comment by iamdefinitelyahuman** [comment]
```python
  File "brownie/exceptions.py", line 91, in __init__
    raise ValueError(exc["message"]) from None
ValueError: Returned error: missing trie node 209230089ff328b2d87b721c48dbede5fd163c3fae29920188a7118275ab2013 (path )
```
