### ISSUE TITLE
Cannot use POA networks without web3 middleware

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#583]
### What was wrong?
Brownie cannot use POA networks such as Rinkeby:

```python
$ brownie console --network rinkeby
Brownie environment is ready.

>>> web3.eth.getBlock('latest')
  File "web3/middleware/validation.py", line 64, in check_extradata_length
    raise ValidationError(
ValidationError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes('0xd88301090e846765746888676f312e31342e32856c696e757800000000000000f7c64a4f0cae89e657eeb51811c451d11c4ed6e04468c7d4f8343521c77348560343fbe65619d6ffcd698e8be87b74cf6125235d010f6f21571f0ac9ce2d730101')
```

### How can it be fixed?

We must implement the `geth_poa_middleware`. From the web3 [docs](https://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority):

> There is no strong community consensus on a single Proof-of-Authority (PoA) standard yet. Some nodes have successful experiments running, though. One is go-ethereum (geth), which uses a prototype PoA for it’s development mode and the Rinkeby test network.

> Unfortunately, it does deviate from the yellow paper specification, which constrains the extraData field in each block to a maximum of 32-bytes. Geth’s PoA uses more than 32 bytes, so this middleware modifies the block data a bit before returning it.

I see two potential solutions:

* Add a network settings flag to indicate that a network is POA, which triggers adding the middleware.
* Upon connecting to a new network, make an RPC call and catch `web3.exceptions.ValidationError` if raised. If the exception message includes a mention of too much `extraData`, add the middleware.

**Comment by matnad** [comment]
As long as this is just an issue with rinkeby, I would avoid adding a setting or flag.
If automatic detection is reliable, I see no reason not to use that

**Comment by iamdefinitelyahuman** [comment]
Handling this upstream first - https://github.com/ethereum/web3.py/pull/1666

Catching a more targeted exception is a far better approach than catching `ValidationError` and checking for a reference to `extraData` in the exception string.

**Comment by iamdefinitelyahuman** [comment]
web3 just pushed a new release, this can be implemented!
