### ISSUE TITLE
User-defined wait time for broadcasted transactions

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#587]
### Overview
Allow users to specify the number of confirmations they wish to wait for a transaction.

### Specification
When broadcasting a transaction, the `required_confs` kwarg can determine how many confirmations to wait for.  Value can be 0 for a non-blocking action that returns a pending `TransactionReceipt`.  The default value is 1.

```python
accounts[0].transfer(accounts[1], required_confs=n)
Token.transfer(accounts[1], 10000, {'from': accounts[0], 'required_confs': n)
```

Once a tx is broadcast, it should also be possible to wait for confirmations via a `wait` method.  If the number of confirmations is already greater than `n`, nothing happens.

```python
tx.wait(n)
```

Once this is added, the old and half-broken logic around `CTRL-C` in the console can also be removed.

**Comment by matnad** [comment]
starting on this
