### ISSUE TITLE
Add an object for easy access to block data

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#611]
### Overview
Add a new object to allow easy access to block data from [`web3.eth.getBlock`](https://web3py.readthedocs.io/en/stable/web3.eth.html).

### Specification
Create a singleton list-like container object called `chain`.

Accessing the list with positive index values returns the given block:

```python
chain[0] == web3.eth.getBlock(0)
chain[42] == web3.eth.getBlock(42)
```

Accessing with negative indexes returns blocks relative to the latest block:

```python
chain[-1] == web3.eth.getBlock('latest')

number = web3.eth.getBlock('latest')['number']
chain[-42] == web3.eth.getBlock(number - 42)
```

`len` returns the current block number of blocks.

```python
len(chain) == web3.eth.blockNumber + 1  # add one because the first block is 0
```

Related to #254, this object could also be the new home for `Rpc` methods related to time travel, snapshotting, and mining:

```
chain.sleep(1000)
chain.mine(3)
chain.undo()
```

### Dependencies
Some aspects of this proposal are breaking, but we could add the new object immediately and mark the `Rpc` methods as deprecated without removing them until `v2.0.0`.

**Comment by matnad** [comment]
I think it would make sense to cache the accesses blocks for the session, maybe with a limit?

**Comment by iamdefinitelyahuman** [comment]
Yeah definitely!  We should look at etherscan to see what the upper bound on uncle length is.
