### ISSUE TITLE
Add address key to Event

### ISSUE THREAD

**Issue by WyseNynja** [eth-brownie/brownie#670]
### Overview

I am trying to read the logs from a transaction to Compound. The "Transfer" event has "from", "to", and "value". The log has "address" (and other things). It would be nice if the event also had the address.

For now I can use `pos = tx.events["Transfer"].pos[0]` and then `tx.logs[pos].address`

**Comment by iamdefinitelyahuman** [comment]
Adding `"address"` as a field to the `_EventItem` object would be too ambiguous re: was this a field in the event?  But I think we can expose it as an attribute:

```python
>>> tx.events["Transfer"][0].address
"0xF9c1fd2f0452FA1c60B15f29cA3250DfcB1081b9"
```
