### ISSUE TITLE
Allow importing contracts inside test suites

### ISSUE THREAD

**Issue by fubuloubu** [eth-brownie/brownie#719]
### Overview
Brownie provides contract types as fixtures, however it would be helpful to also allow importing them via `from brownie import ContractType`, then you could do useful stuff like [this](https://docs.pytest.org/en/stable/fixture.html#parametrizing-fixtures):
```python
import pytest
from brownie import ProtocolV1, ProtocolV2

@pytest.fixture(params=[ProtocolV1, ProtocolV2])
def protocol(accounts, request):
    yield accounts[0].deploy(request.param)
```

This would parametrize the fixture such that it would run any tests it touches twice, once with `ProtocolV1`, and once with `ProtocolV2`.

**Comment by iamdefinitelyahuman** [comment]
This does work in tests, but not in `conftest.py` apparently.  Shouldn't be a hard fix, just need to ensure the project is loaded before plugin collection happens.
