### ISSUE TITLE
Allow manual repricing of pending transactions

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#726]
### Overview
It should be simple to reprice a pending transaction.

### Specification
In the console, with a `TransactionReceipt` object that's still pending:

```
>>> tx.reprice(gas_price)
```

Once this is done, the logic in `TransactionReceipt._await_confirmation` must watch both pending transactions - it could still be possible that the original one confirms before the higher-priced one is seen by the miner.

### Dependencies
None.

**Comment by cygnusv** [comment]
Have you seen `web3._utils.transactions.prepare_replacement_transaction`? I realized very recently it was there all along 🙈
