### ISSUE TITLE
brownie pm export results in Invalid command

### ISSUE THREAD

**Issue by nopslip** [eth-brownie/brownie#769]
### Environment information

* `brownie` Version: v1.11.5
* `ganache-cli` Version: 6.10.2
* Python Version: 3.8.5
* OS: osx

### What was wrong?

`brownie pm export OpenZeppelin/openzeppelin-contracts@3.2.1-solc-0.7`

Results in: 

```
Brownie v1.11.5 - Python development framework for Ethereum
Invalid command. Try brownie pm --help
```

Looks like `export` command has been replaced with `clone`:

`brownie pm --help`

```
Brownie v1.11.5 - Python development framework for Ethereum

Usage: brownie pm <command> [<arguments> ...] [options]

Commands:
  list                          List available accounts
  install <uri> [version]       Install a new package
  clone <id> [path]             Make a copy of an installed package
  delete <id>                   Delete an installed package

Options:
  --help -h                     Display this message
```

### How can it be fixed?
Probably just a matter of updating the docs at https://eth-brownie.readthedocs.io/en/latest/package-manager.html#exporting-a-package - Assuming that is correct I could update the docs.

**Comment by iamdefinitelyahuman** [comment]
Ahh, good catch!  Yes, the correct command is `clone`.. happy to receive a PR to fix :pray:
