### ISSUE TITLE
Brownie does not generate compilation artifacts for dependencies

### ISSUE THREAD

**Issue by montyly** [eth-brownie/brownie#772]
Hi,

### Overview
When running `brownie compile`, the compilation artifacts for the dependencies will not be generated in `build/contracts/`. This prevents third-party tools to analyze the contracts (for example https://github.com/crytic/slither/issues/638)

It would be great if all the json could be available after compilation

**Comment by iamdefinitelyahuman** [comment]
The artifacts are available at `~/.brownie/packages/[org]/[repo]@[version]/build/contracts` - but, that's not a very nice path to expect a 3rd party integration to find.

Would it work if a project's dependency artifacts were added at `build/contracts/dependencies/[org]/[repo]@[version]/` ? Separate folders will ensure no chance for namespace collision.

**Comment by Macarse** [comment]
`slither .` runs against the JSON files in the build directory.

I was comparing two projects, https://github.com/hegic/contracts-v1 using truffle to compile which works fine and https://github.com/iearn-finance/yearn-protocol using brownie which fails.

When I compared the JSON files created in the build directory, the working version has something like:
```
      {
        "absolutePath": "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        "file": "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        "id": 2075,
        "nodeType": "ImportDirective",
        "scope": 2147,
        "sourceUnit": 3091,
        "src": "772:55:5",
        "symbolAliases": [],
        "unitAlias": ""
      }
```

and the broken version looks like:
```
      {
        "absolutePath": "/my_home/.brownie/packages/OpenZeppelin/openzeppelin-contracts@2.5.1/contracts/token/ERC20/ERC20.sol",
        "file": "@openzeppelinV2/contracts/token/ERC20/ERC20.sol",
        "id": 12383,
        "nodeType": "ImportDirective",
        "scope": 12409,
        "sourceUnit": 17334,
        "src": "58:57:24",
        "symbolAliases": [],
        "unitAlias": ""
      },
```

If the path to the import is properly set in the JSON file, isn't slither not paring the JSON correctly?

**Comment by Macarse** [comment]
@iamdefinitelyahuman I have been playing with this issue.

I have compared a project built with truffle which works with slither (https://github.com/hegic/contracts-v1) and a project built with brownie which doesn't work (https://github.com/iearn-finance/yearn-protocol).

I removed most of the files from yearn-protocol leaving a single file, https://github.com/iearn-finance/yearn-protocol/blob/develop/contracts/test/Token.sol, so it's easier to debug. Slither creates a dictionary of core contract definitions and here's the output of yearn-protocol with the single Token contract.
```
SlitherSolcParsing:cores {'Token': <slither.core.declarations.contract.Contract object at 0x10196cb50>}
```

When debugging slither with the Hegic repo I noticed:

```
INFO:SlitherSolcParsing:cores {'HegicOptions': <slither.core.declarations.contract.Contract object at 0x109a26af0>, 
...
'SafeMath': <slither.core.declarations.contract.Contract object at 0x10971b0d0>,....
```

Both `HegicOptions` and `SafeMath` are json files in `/build/contracts`.
I have tried copying all the JSON files in `~/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/build/contracts/*` but this still doesn't work :(

I haven't dig into truffle's logic yet, but they are not copying/compiling the whole openzeppelin library, just a few contracts. Do you know why truffle moves the json files to the project's build/contracts dir?

**Comment by iamdefinitelyahuman** [comment]
My guess is truffle considers all files that are imported to be a part of the core project, whereas brownie does not.

To prevent potential namespace collisions I think the easiest approach is to keep the dependencies in a subdirectory of `build/contracts`, probably using the same structure as they're kept in `~/.brownie/packages`.  I'm not sure if slither will look in subdirectories, but if not it probably wouldn't be hard to implement.

**Comment by Macarse** [comment]
@iamdefinitelyahuman I tried copying the json files by hand and that didn't work either.
Truffle doesn't just copy the files, if I compare the json in `node_modules` is different from the json in the `build` directory.
(I don't know how that affects the process and what difference it makes)

How does it work with brownie? Who compiles the jsons in the `~/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/build/contracts/*`?

**Comment by iamdefinitelyahuman** [comment]
Compilation is triggered in `brownie.project.main::install_package`, when the package is first installed.  Projects are then able to import from the packages because `~/.brownie/packages` is automatically included in `solc`'s allowed paths.

**Comment by montyly** [comment]
Hi @iamdefinitelyahuman, if the files are copied into `build/contracts/dependencies/[org]/[repo]@[version]/` it will work for slither.

We could make it work with `~/.brownie`, but looking only into the local folder is probably a cleaner option.

**Comment by sssubik** [comment]
Hey @montyly "if the files are copied into `build/contracts/dependencies/[org]/[repo]@[version]/ `it will work for slither" Can we do this for openzeppelin stuff?
If yes what are org repo and version? Like how should the folder structure be??

**Comment by montyly** [comment]
Hi @sssubik .

We will have a new release for [`crytic-compile`](https://github.com/crytic/crytic-compile/) in the upcoming days that will include the support for the dependencies in brownie. 

However, I noticed another issue (https://github.com/eth-brownie/brownie/issues/941), which can prevent slither from working on brownie for codebases with interfaces

**Comment by sssubik** [comment]
Hey @montyly Thanks for the response. Can I do this now manually by copying json files from .brownie folder? 
Like how should the build folder be for that??
