### ISSUE TITLE
Deploy script error – ValueError: '0x0' is not a valid ETH address

### ISSUE THREAD

**Issue by bogatyy** [eth-brownie/brownie#794]
### Environment information

* `brownie` Version: 1.11.7
* `ganache-cli` Ganache CLI v6.0.3 (ganache-core: 2.0.2)
* `solc` Version: 0.5.17
* Python Version: 3.7.4
* OS: OsX

### What was wrong?

Ran the standard deploy script on the Brownie cookie-cutter app template.
Error message:
```python
>>> run("deploy")

Running 'scripts/deploy.py::main'...
Transaction sent: 0xc41c5a946e7dd4d020912dcf57def4a445cfe71247b157ac2e15cf33641c5f1a
  File "<console>", line 1, in <module>
  File "brownie/project/scripts.py", line 66, in run
    return getattr(module, method_name)(*args, **kwargs)
  File "./scripts/deploy.py", line 6, in main
    accounts[0].deploy(SolidityStorage)
  File "brownie/network/account.py", line 455, in deploy
    revert_data=revert_data,
  File "brownie/network/transaction.py", line 167, in __init__
    self._await_transaction(required_confs)
  File "brownie/network/transaction.py", line 296, in _await_transaction
    self._set_from_tx(tx)
  File "brownie/network/transaction.py", line 362, in _set_from_tx
    self.receiver = EthAddress(tx["to"]) if tx["to"] else None
  File "brownie/convert/datatypes.py", line 204, in __new__
    raise ValueError(f"'{value}' is not a valid ETH address") from None
ValueError: '0x0' is not a valid ETH address
```

### My temporary fix

The culprit seems to be here: https://github.com/eth-brownie/brownie/blob/master/brownie/network/transaction.py#L362
Fixed by changing:
```
-self.receiver = EthAddress(tx["to"]) if tx["to"] else None
+self.receiver = EthAddress(tx["to"]) if tx["to"] and tx["to"] != "0x0" else None
```

Why is this bug triggering for me? Seems like an issue that should appear pretty frequently for anyone deploying contracts?

**Comment by iamdefinitelyahuman** [comment]
You're using a fairly old version of ganache.  Can you try updating and see if the issue persists?

**Comment by bogatyy** [comment]
Updated ganache, started working indeed.
My bad: installed the latest ganache yesterday, but turns out wrong PATHs prioritized the ancient pre-existing version by default.
Thank you!
