### ISSUE TITLE
Allow regex in `brownie.reverts`

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#807]
### Overview
It should be possible to match revert strings using regex.

### Specification
Instead of the current check of `revert_msg == expected_msg`, use `re.fullmatch(expected_msg, revert_msg)`. This will allow regext while still providing the same matching capability when regex isn't used.

cc @banteg

**Comment by Alireza-Sampour** [comment]
@iamdefinitelyahuman Hi, I'd like to take this up. Please specify, which file needs change

**Comment by iamdefinitelyahuman** [comment]
@Alireza-Sampour thanks!  The change is to the `RevertContextManager` in `brownie/test/managers/runner.py`
