### ISSUE TITLE
Add marker to only run tests in a specific environment

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [eth-brownie/brownie#810]
### Overview
It should be easy to skip a test unless a specific network is in use.

https://ethereum.stackexchange.com/questions/88262/setup-brownie-to-run-certain-test-in-a-specific-network

### Specification
I'm not 100% on the best name, but I think a marker makes the most sense.  Something like this:

```python
@pytest.mark.active_network('mainnet-fork')
def test_almost_in_prod():
    ...
```

```python
@pytest.mark.active_network('development')
def test_locally():
    ...
```

**Comment by Macarse** [comment]
sounds like pytest markers are a good solution.
wdyt of `@pytest.mark.require_network('development')` so I only mark the ones that depend on a certain network being used.

**Comment by iamdefinitelyahuman** [comment]
yes, `require_network` is much clearer than `active_network`.  I like it!
