### ISSUE TITLE
Integration with Local Ropsten/Rinkeby Geth Node

### ISSUE THREAD

**Issue by dendisuhubdy** [eth-brownie/brownie#822]
Hi guys,

Super awesome work, but it seems I cannot find any pointers anywhere on how to connect brownie to a local run ropsten/rinkeby geth node? Can someone point out to be how to do this with Brownie?

Dendi

**Comment by dendisuhubdy** [comment]
Sorry found something here https://eth-brownie.readthedocs.io/en/latest/config.html#the-configuration-file

**Comment by iamdefinitelyahuman** [comment]
I think this section of the docs will be more useful: https://eth-brownie.readthedocs.io/en/stable/network-management.html

**Comment by dendisuhubdy** [comment]
@iamdefinitelyahuman thanks Ben!

**Comment by dendisuhubdy** [comment]
@iamdefinitelyahuman ok sorry for reopening the issue, I realize when I scrolled to the bottom I didn't find any explanation on connecting brownie via RPC to Rinkeby/Ropsten on Geth?

I'm running geth via ```geth --rinkeby console --ipcpath "/Users/dendisuhubdy/Library/Ethereum/rinkeby/geth.ipc" --http```

How do you specify connecting to Rinkeby via the brownie config? Can you show an example?

I might want to write some docs https://eth-brownie.readthedocs.io/en/stable/network-management.html to help other people out too!

**Comment by dendisuhubdy** [comment]
<img width="736" alt="Screen Shot 2020-10-23 at 21 04 37" src="https://user-images.githubusercontent.com/4477337/97013548-5f58a780-1573-11eb-9c00-7589693bc0be.png">

**Comment by iamdefinitelyahuman** [comment]
You just have to add a network, or modify the config for an existing network:

https://eth-brownie.readthedocs.io/en/stable/network-management.html#adding-a-new-network

The settings are stored at `~/.brownie/network-config.yaml`, sometimes it's easier to edit that manually rather than use the CLI.

Once you're done editting, connect by using `--network [name]` as a flag when running brownie.

**Comment by dendisuhubdy** [comment]
Thank you @iamdefinitelyahuman
