### ISSUE TITLE
User shouldn't be able to modify contracts methods

### ISSUE THREAD

**Issue by Macarse** [eth-brownie/brownie#837]
### Environment information

* `brownie` Version: 1.11.11
* `ganache-cli` Version: N/A
* `solc` Version: 0.6.12
* Python Version: 3.8.6
* OS: osx

### What was wrong?
My solidity contract defines:

```
bool public variable;
```

and from the `brownie console` I can do things like:
```contract.variable = True```
when I shouldn't be able to.

**Comment by iamdefinitelyahuman** [comment]
Fixed in #855
