### ISSUE TITLE
Unable to compile dependency

### ISSUE THREAD

**Issue by Macarse** [eth-brownie/brownie#845]
### Environment information

* `brownie` Version: 1.11.12 / 3fad0bdc7a65cd1c27d23c0dda4a5276f7255670 (locally)
* `ganache-cli` Version: N/A
* `solc` Version: 0.6.12
* Python Version: 3.8.6
* OS: osx

### What was wrong?
I am trying to add a dependency to another project and I am getting:
```
WARNING: Unable to compile Macarse/GenericKeep3rV2@0.0.1 due to a FileNotFoundError - you may still be able to import sources from the package, but will be unable to load the package directly.
```
Dependency is https://github.com/Macarse/GenericKeep3rV2/releases/tag/0.0.1

Please include information like:
I run brownie locally to find out more.
I added a `print(str(e))` to the warning  and the apparent file missing is: `interfaces/IKeep3rV1.sol`

I kept looking at the brownie code and found the exception happening at:
`changed_sources = {i: self._sources.get(i) for i in changed_paths}` in the `_compile_interfaces` method.
I tried shuffling the `changed_sources` array and all of them seem to be failing.

No idea what the `change_sources` is for.
Any idea what can be wrong?

**Comment by Macarse** [comment]
Some additional info:
Copy-pasting from the `GenericKeep3rV2` `contracts` and `interfaces` content into the new project works fine.

**Comment by iamdefinitelyahuman** [comment]
Not sure what this is, but i'll investigate.

**Comment by Macarse** [comment]
Thanks a lot!
