### ISSUE TITLE
dropped and replaced transaction hangs brownie while repeatedly hitting infura 18,091 times with eth_getTransactionReceipt

### ISSUE THREAD

**Issue by sabotagebeats** [eth-brownie/brownie#850]
### Environment information

* `brownie` Version: v1.11.0
* `ganache-cli` Version: v6.10.1 (ganache-core: 2.11.2)
* `solc` Version: 
* Python Version: 3.8.5 
* OS: win 10

### What was wrong?

Please include information like:

sent a transaction
transaction was dropped and replaced on etherscan
no error, just repeatedly hi infura 18,091 while waiting for transaction to confirm for 4 hours

### How can it be fixed?

Fill this in if you know how the bug could be fixed.
if transaction is dropped and replaced it should work with the replaced transaction

**Comment by sabotagebeats** [comment]
![image](https://user-images.githubusercontent.com/27985126/99758172-d9fae100-2aa5-11eb-9966-4a5ab7c6d814.png)

**Comment by iamdefinitelyahuman** [comment]
Oh my :grimacing: Was the replacement transaction broadcast within Brownie or via another program?

I _think_ this was fixed in #846 but I'll have a look again to be sure.

**Comment by sabotagebeats** [comment]
I believe it's from using the same account key in different instances of brownie console simultaneously so the nonce is not getting updated.

**Comment by sabotagebeats** [comment]
I will try updating brownie and also try using different keys for different simultaneously executing transactions

**Comment by sabotagebeats** [comment]
Haven't experienced this since recent versions. Closing issue and will reopen if I encounter the problem again.
