### ISSUE TITLE
Values not seen in stack trace

### ISSUE THREAD

**Issue by visopsys** [eth-brownie/brownie#871]
### Environment information

* `brownie` Version: 1.12.0
* `ganache-cli` Version: v6.12.0
* `solc` Version: 0.6.0
* Python Version: 3.6.8
* OS: MacOS

### What was wrong?
I create a simple contract that raises an exception in the console. I use `tx.call_trace(True)` but I can only see function calls and not values associated with it. Here is my stacktrace:

```
>>> tx.call_trace(True)
Call trace for '0xe172cc35c279578886c7d244bee59e6afe31d7d846820e2493e715f401abb21c':
Initial call cost  [21620 gas]
Token.transfer  0:304  [275 / 1940 gas]
└── ERC20.transfer  72:304  [39 / 1665 gas]
    ├── Context._msgSender  78:82  [14 gas]
    └── ERC20._transfer  87:304  [1080 / 1612 gas]
        ├── ERC20._beforeTokenTransfer  114:119  [15 gas]
        └── SafeMath.sub  162:304  [517 gas]
```

However, Vasa was able to see values in his stacktrace [here](https://pastebin.com/pJfwR0av). My full conversation with Vasa on Twitter is [here](https://twitter.com/vasa_develop/status/1332776598580457474).

Did I do anything wrong? 

### How can it be fixed?

No idea.

**Comment by iamdefinitelyahuman** [comment]
Unfortunately, detailed information is only available for external contract calls.  Internal calls between functions do not provide this info.  Sorry!

**Comment by visopsys** [comment]
Thanks for clarification @iamdefinitelyahuman
