### ISSUE TITLE
Solidity compilation broken for solc0.8.0

### ISSUE THREAD

**Issue by sinasabet81** [eth-brownie/brownie#897]
### Environment information

* `brownie` Version: v1.12.2
* `ganache-cli` Version: 6.12.1
* `solc` Version: 0.8.0
* Python Version: 3.8
* OS: osx/linux/win

### What was wrong?

I think brownie's solidity compatibility may be broken for solidity version 0.8.0.

To reproduce, create a solidity contract and try to compile it with solc 0.8.0 via `brownie compile`. Here's a minimal contract I was able to reproduce with:
```
pragma solidity 0.8.0;

contract Testy {
    address public testAddress;
    constructor() public {}
}
```

when I try to run `brownie compile --all`, I get this error:
![image](https://user-images.githubusercontent.com/3280221/102597888-1daa3000-40d0-11eb-8334-f769c8bfbac0.png)

### How can it be fixed?

By changing the solidity version to something else. For example, when I change the solidity version in the file to something like `0.6.0`, it appears to compile without issue.

From my brief tinkering, it looks like 0.8.0 is the first version that this breaks (ie. it compiles fine on 0.7.6).

**Comment by iamdefinitelyahuman** [comment]
This appears to be the same bug as #890, there is a fix in #895 but the CI is showing other, unrelated issues with 0.8.0 that still need addressing :grimacing: 

Thanks for the minimal example, it will be useful for writing some tests around this.
