### ISSUE TITLE
Add conda-forge recipe

### ISSUE THREAD

**Issue by spinoch** [eth-brownie/brownie#902]
Add a recipe to https://github.com/conda-forge/staged-recipes to have brownie available as a package on `conda-forge`, so that brownie can be installed using `conda`.

Not all of brownie's dependencies are available as conda packages, though, so we may want to look into adding recipes for those before we add a recipe for brownie (it shouldn't take more than a few minutes if the package specification is up to date).
Those packages are:

eth-event
py-solc-ast
pygments-lexer-solidity
pythx
vvm
vyper (xref: https://github.com/vyperlang/vyper/issues/2214)

**Comment by iamdefinitelyahuman** [comment]
I'm fully in support of this, but unfamiliar with how conda works.  I'm the principal maintainer of `eth-event`, `py-solc-ast`, and `vvm` so consider them in support as well.

I'll reach out to you on telegram to discuss.

**Comment by spinoch** [comment]
We now have most dependencies on conda-forge, but we're missing a few for which I haven't yet found any maintainers apart from myself: ` pygments-lexer-solidity`, `pythx`, `web3` and one more (the state of Ethereum python packages is messier than I thought).
Any volunteers that would like to step up as a _maintainer_ of these conda packages? I'd rather not be just myself as maintainer as having a bus factor of 1 is not very resilient

**Comment by spinoch** [comment]
Will close this for now given the state of Ethereum Python packages on which brownie depends.
Unfortunate, as this would have resolved environments getting corrupted because of pytest conflicts

**Comment by spinoch** [comment]
Well, all deps are on conda-forge now, but for some reason, even with soft pinning, `grayskull` still gives me an old version for `mythx-models` (1.9.1 to be precise).
For the hard pinning version, the following dependency versions are not on conda atm:
```
conda.exceptions.ResolvePackageNotFound: 
  - lru-dict==1.1.7
  - pythx==1.6.1
  - pygments-lexer-solidity==0.5.1
  - web3==5.11.1
  - mythx-models==1.9.1
  - netaddr==0.8.0
```

**Comment by calina-c** [comment]
Hello, all! I know this is an older issue but maybe it is time to revive it. I tried running grayskull and the only dependency that is missing is `eip712`. A grayskull run for `eip712` works perfectly, no missing dependencies on their side. Is it worth exploring this, maybe opening a request with them? If `eip712` adds a conda recipe, then it's all clear for brownie as well.

**Comment by spinoch** [comment]
@calina-c by all means, go ahead and add a recipe for `eip712`. You can add me as maintainer if you want. Same goes for brownie

**Comment by calina-c** [comment]
@spinoch https://github.com/conda-forge/staged-recipes/pull/22056

**Comment by calina-c** [comment]
@spinoch unfortunately I can't add both packages in the same PR, but I added eip712 for now. I tagged you as a maintainer and you need to confirm in that PR that you agree. I'll come back with the brownie recipe after eip712 is confirmed and merged. Thank you a lot!

**Comment by calina-c** [comment]
I haven't heard about this one in a while, so I'm commenting again. @spinoch are you still up to be a maintainer? Or should I add someone else?
