### ISSUE TITLE
Add support for Openzepplin's  Upgrade plugin

### ISSUE THREAD

**Issue by PatrickAlphaC** [eth-brownie/brownie#929]
### Overview
I haven't looked into it enough to determine the feasibility (as it's written in js), but openzepplin's upgrade plugin is a really powerful tool for building applications with minimal and upgradeable proxies. 

This would make it easy to have out-of-the box functionality to deploy smart contracts with a proxy, making them easier to upgrade. 

For reference, see: https://docs.openzeppelin.com/upgrades-plugins/1.x/

Not exactly sure what this would look like, and I'm aware you can map openzepplin in brownie with the mapping feature but might be nice to have built-in support. 

This is more of an idea than a fully thought out issue.

**Comment by iamdefinitelyahuman** [comment]
I think related to https://github.com/eth-brownie/brownie/issues/867

**Comment by PatrickAlphaC** [comment]
Yes, you're right. I'll close this!
