### ISSUE TITLE
Add support for EVM Compatible side-chains

### ISSUE THREAD

**Issue by PatrickAlphaC** [eth-brownie/brownie#934]
### Overview
Provide a simple overview of what you wish to see added. Please include:

As L2's become more popular, more and more people will be looking at side chains like Matic, xDai, and Optimism to deploy their smart contracts. Having native integrations for Brownie would be an easy way for engineers to start using the with Brownie. 

### Specification
On the networks config page, maybe add an EVM-side-chain or something. And underneath have `mumbai` and `sokol` for starters (Matic testnet and xDai testnet)

Literally, everything else is the same.

For reference, I have deployed on these two chains with Brownie here, for [Matic](https://github.com/PatrickAlphaC/matic-brownie) and [xDai](https://github.com/PatrickAlphaC/xDai-brownie).

**Comment by skgbanga** [comment]
As matic' popularity has exploded in recent times, it would be great to have matic mainnet (and matic mumbai testnet) directly included in brownie.

**Comment by iamdefinitelyahuman** [comment]
Specific to matic, it wasn't easily supported until just a couple of days ago when polygonscan came online.  Not having an API to pull sources and ABIs from significantly reduces the brownie user experience.  Now that polygonscan is live, matic support should be present in the next release.

I'm also speaking to the blockscout team about adding an API, so then we can properly support chains that use it (notably xdai).
