### ISSUE TITLE
Generated event topic is incorrect for events with dynamic size tuple inputs

### ISSUE THREAD

**Issue by skellet0r** [eth-brownie/brownie#955]
### Environment information

* `brownie` Version: 1.13.1
* `ganache-cli` Version: 6.12.2
* `solc` Version: 0.7.6
* Python Version: 3.9.1
* OS: linux
* `eth-event` Version: 1.2.0

### What was wrong?

The generated log topic for events with dynamic size tuple inputs is incorrect.
See iamdefinitelyahuman/eth-event#15 for more information.

This issue will have to be fixed upstream in the `eth-event` package, and then after a new release, the dependency will have to be bumped.

**Comment by iamdefinitelyahuman** [comment]
https://github.com/iamdefinitelyahuman/eth-event/releases/tag/v1.2.1

Should be solved upstream, just need to bump the minimum version in `requirements.txt`
