### ISSUE TITLE
Get rich transaction from hash

### ISSUE THREAD

**Issue by jannikluhn** [eth-brownie/brownie#966]
I have a contract object and the hash of a transaction calling said contract. I would like to get

- the function that was called and the list of arguments
- the parsed events emitted

Is this possible? I know I can use `web3.eth.getTransaction` and `web3.eth.getTransactionReceipt`, but this only gives me the raw calldata/logs.

**Comment by iamdefinitelyahuman** [comment]
```

**Comment by jannikluhn** [comment]
thank you, that's exactly what I was looking for, but couldn't find
