### ISSUE TITLE
Getting psutil.AccessDenied error on each and every run

### ISSUE THREAD

**Issue by fedor-ivn** [eth-brownie/brownie#992]
### Environment information

* `brownie` Version: 1.13.4
* `ganache-cli` Version: latest (runs in docker container with standard parameters)
* `solc` Version: doesn't really matter
* Python Version: 3.9
* OS: osx (Catalina)

### What was wrong?

I'm getting this error on each and every run of any brownie command. I've googled it, but haven't found any solutions. I suppose it's a trouble of MacOS, but I am not sure.

I am running brownie only with `sudo` know, but this approach has some limitations and cannot be considered as a solution.

```
Brownie v1.13.4 - Python development framework for Ethereum

ContractsProject is the active project.
  File "brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/run.py", line 43, in main
    network.connect(CONFIG.argv["network"])
  File "brownie/network/main.py", line 48, in connect
    rpc.attach(host)
  File "brownie/network/rpc.py", line 156, in attach
    pid = _find_rpc_process_pid(resolved_addr)
  File "brownie/network/rpc.py", line 264, in _find_rpc_process_pid
    i for i in psutil.net_connections(kind="tcp") if _check_net_connections(i, laddr)
  File "psutil/__init__.py", line 2153, in net_connections
    return _psplatform.net_connections(kind)
  File "psutil/_psosx.py", line 249, in net_connections
    cons = Process(pid).connections(kind)
  File "psutil/_psosx.py", line 351, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=43460)
```

### How can it be fixed?
I would like to know :) I've checked the issues, but haven't found any corresponding.
Maybe someone faced the same problem?

**Comment by iamdefinitelyahuman** [comment]
Related to https://github.com/eth-brownie/brownie/pull/972 - seems there's an issue with using [`psutil.net_connections`](https://psutil.readthedocs.io/en/latest/index.html?highlight=net_connections#psutil.net_connections) on OSX.  Not sure immediately what the solution is.

**Comment by mariuspod** [comment]
hey, just looked into the docs and found this: https://github.com/giampaolo/psutil/issues/1219

It seems on OSX privileged connections can't be queried atm.
The author of psutil says lsof on OSX does the same :-/

Maybe it's possible to try-catch around it and if we're lucky the pid of the docker container runs in unprivileged scope.
The known workaround is to run:

```bash
sudo brownie
```
I'll try to find a test OSX machine :sweat_smile:

**Comment by mariuspod** [comment]
@iamdefinitelyahuman 
here's a draft PR fixing the issue on OSX: https://github.com/eth-brownie/brownie/pull/995
Need to make it a bit more clean and try to add some tests. :sweat_smile: 

Basically, the actual docker process can be queried for connections. The exception occurs only while other privileged processes are queried which have nothing to do with the dockerized ganache.

**Comment by iamdefinitelyahuman** [comment]
Awesome, thank you for solving this!

**Comment by fedor-ivn** [comment]
Hey there! Thanks for paying attention to my problem, I appreciate that. 

I've updated `eth-brownie` package through pip, but unfortunately, I still have the same problem.

Here's the traceback:
```
  File "brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/run.py", line 43, in main
    network.connect(CONFIG.argv["network"])
  File "brownie/network/main.py", line 48, in connect
    rpc.attach(host)
  File "brownie/network/rpc/__init__.py", line 114, in attach
    pid = _find_rpc_process_pid(resolved_addr)
  File "brownie/network/rpc/__init__.py", line 195, in _find_rpc_process_pid
    i for i in psutil.net_connections(kind="tcp") if _check_net_connections(i, laddr)
  File "psutil/__init__.py", line 2153, in net_connections
    return _psplatform.net_connections(kind)
  File "psutil/_psosx.py", line 249, in net_connections
    cons = Process(pid).connections(kind)
  File "psutil/_psosx.py", line 351, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=93950)
```

**Comment by iamdefinitelyahuman** [comment]
Unless you install directly from `master` here on github, the fix isn't available just yet.  Once #1006 merges, hopefully will be a different story :)

**Comment by fedor-ivn** [comment]
Oh, sure, thanks. I'll be waiting :)

**Comment by mariuspod** [comment]
@fedor-ivn 
if you want to test the fix and install master branch of brownie via pip you can try:
```bash
pip3 install git+https://github.com/eth-brownie/brownie
```
